### ISSUE TITLE
Drop pyparsing dependency

### ISSUE THREAD

**Issue by jhjaggars** [RedHatInsights/insights-core#1]
_From @jhjaggars on May 24, 2017 17:13_

This currently includes rewriting all the RabbitMQ mappers. The multipath mapper already has a non-pyparsing implementation, but it just needs to be merged.

_Copied from original issue: RedHatInsights/falafel#248_

**Comment by JoySnow** [comment]
@xiangce , the pyparsing parsers' usage were also replaced in Insights rules. Do you think we can close this issue here?

**Comment by xiangce** [comment]
Yes, closing it.
