### ISSUE TITLE
Support Python Version 2.6.x

### ISSUE THREAD

**Issue by jhjaggars** [RedHatInsights/insights-core#10]
_From @jhjaggars on May 24, 2017 17:8_

This change really means supporting both runtimes, we aren't looking to take advantage of language feature changes.

_Copied from original issue: RedHatInsights/falafel#244_

**Comment by csams** [comment]
YAMLParser depends on pyyaml, [which supports 2.7 and 3.4+](http://pyyaml.org/wiki/PyYAML#Requirements).

A replacement candidate is [ruamel](https://pypi.python.org/pypi/ruamel.yaml/0.6).

**Comment by gavin-romig-koch** [comment]
@jhjaggars Why 2.6.x instead of 2.7.x?

**Comment by bfahr** [comment]
@jhjaggars I think we've implemented 2.6 support, what about 3.3 support?

**Comment by jhjaggars** [comment]
@bfahr 3.3 support has not been started just yet.

**Comment by jhjaggars** [comment]
Turns out, this is more complex than even anticipated.  RHEL6, which ships python 2.6 actually packages and supports pyyaml.  So, for RHEL we support python 2.6, but for other distros we support python 2.7 currently.  I'm OK with this for now, but I admit that it's hokey.

**Comment by jhjaggars** [comment]
@gavin-romig-koch Sorry, missed your question.  The reason we want to support python2.6 is for RHEL6 support.
