### ISSUE TITLE
Insights core tests should use Insights Demo Plugins repository as a test bed

### ISSUE THREAD

**Issue by PaulWay** [RedHatInsights/insights-core#1009]
Once the 3.0 branch is considered stable, how about we use the Insights Demo Plugins repository:

https://github.com/RedHatInsights/insights-plugins-demo

as a test bed?  This would provide a basic 'integration' level test that the rule evaluation and test system works.

**Comment by jhjaggars** [comment]
Hey @PaulWay,

I think this could be a nice addition to the automated testing we do.  Looks like you'll want to update the repo to handle the changes to the rules api for 3.0 (e.g. replace local, shared, updates to integration test specification, etc...) before we can hook it up.

**Comment by miclark** [comment]
Closing. Will leave this issue to QE to figure out how they want to create integration tests.
