### ISSUE TITLE
`obfuscate_hostname` should require `obfuscate` (BZ1554999)

### ISSUE THREAD

**Issue by gravitypriest** [RedHatInsights/insights-core#1016]
$subject

**Comment by gravitypriest** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1554999

**Comment by kylape** [comment]
Fixed in PR#1066
https://github.com/RedHatInsights/insights-core/commit/b7558f6cddff3a696f6517cc07f87b0e6a976d6c
