### ISSUE TITLE
hostname parser doesn't handle sos_commands/general/hostname

### ISSUE THREAD

**Issue by csams** [RedHatInsights/insights-core#1055]
sos_commands/general/hostname contains the hostname with a newline at the end, which results in a file with two lines. The hostname parser specifically checks for one line but doesn't gracefully handle the problem.

We can update the parser to handle this case and/or investigate whether proc/sys/kernel/hostname is a valid substitute to put in sos_archive.py instead.

**Comment by csams** [comment]
@psachin Hey, sorry for getting back to you late on this. Since pasting between triple quote strings is common when testing large config files or log snippets, `context_wrap` strips the content you pass it before splitting it into lines:
```
    if isinstance(lines, basestring):
        lines = lines.strip().splitlines()
```
Unfortunately, that's hiding the problem in this particular unit test since it'll strip the newlines.

**Comment by psachin** [comment]
@csams That's interesting! That would be older versions of sosreport.

But as you see that new test cases proves that both conditions are handled by parser/context_wrap. It will also give same results while reading multi-line file. Am I missing something?

**Comment by csams** [comment]
@psachin context_wrap is hiding the problem because it's stripping the newlines in your new test cases.

**Comment by csams** [comment]
Fix is in https://github.com/RedHatInsights/insights-core/pull/1112.
