### ISSUE TITLE
Rework core runtime to be like vulcan

### ISSUE THREAD

**Issue by jhjaggars** [RedHatInsights/insights-core#11]
_From @kylape on May 24, 2017 17:8_

Vulcan was renamed to https://github.com/RedHatInsights/falafel-mark2.

_Copied from original issue: RedHatInsights/falafel#243_

**Comment by csams** [comment]
This includes component type name changes (mappers to parsers, etc.), elevating specs to first class components that participate in dependency resolution, and unifying the component evaluation model.

**Comment by jhjaggars** [comment]
I think this is done now.  Can you confirm @csams?
