### ISSUE TITLE
Test of prodsec rules (NFS) are broken

### ISSUE THREAD

**Issue by xiangce** [RedHatInsights/insights-core#1104]
Test result comparing failed as e.g.:
~~~
result = ('/etc/exports.d/foo.exports', [['/u01/app/oracle *(rw,no_root_squash)'], ['/home/nfs/ 10.1.1.0/24(ro,sync) 10.1.1.55(rw,sync,no_root_squash)']])
expected = ('/etc/exports.d/foo.exports', ['/u01/app/oracle *(rw,no_root_squash)', '/home/nfs/ 10.1.1.0/24(ro,sync) 10.1.1.55(rw,sync,no_root_squash)'])
~~~

It's caused by the updating of `raw_lines` in https://github.com/RedHatInsights/insights-core/pull/1086/files#diff-935a59d6d3402fccd96b8d3844f6d106L161, it fixed the old `raw_lines` which only saved the last line and discarded the former lines with the same `path`.

**Comment by xiangce** [comment]
@PaulWay @csams @bfahr - Any thoughts?

**Comment by PaulWay** [comment]
That result looks like the parser is now outputting a list of lists of strings, not a list of strings.

**Comment by PaulWay** [comment]
The current parser tests check for multi-line outputs:
```python
    assert nfs_exports.raw_lines == {
        "/home/utcs/shared/ro": [
            '/home/utcs/shared/ro                    @group(ro,sync)   ins1.example.com(rw,sync,no_root_squash) ins2.example.com(rw,sync,no_root_squash)'
        ], "/home/insights/shared/rw": [
            '/home/insights/shared/rw                @group(rw,sync)   ins1.example.com(rw,sync,no_root_squash) ins2.example.com(ro,sync,no_root_squash)'
        ], "/home/insights/shared/special/all/mail": [
            '/home/insights/shared/special/all/mail  @group(rw,sync,no_root_squash)'
        ], "/home/insights/ins/special/all/config": [
            '/home/insights/ins/special/all/config   @group(ro,sync,no_root_squash)  ins1.example.com(rw,sync,no_root_squash)'
        ], "/home/example": [
            '/home/example                           @group(rw,sync,root_squash) ins1.example.com(rw,sync,no_root_squash) ins2.example.com(rw,sync,no_root_squash)',
            '/home/example                           ins2.example.com(rw,sync,no_root_squash)'
        ]
    }
```
The previous version of the parser did not.  Relying on undefined behaviour is not a good habit to be in :-)

The previous parser seems to have only stored the last line of any path, because of the mistaken assumption that each path can only be defined once in the `exports` file.  This has been corrected to reflect how `exportfs` actually parses exports.

**Comment by matysek** [comment]
I got it fixed in our repo. When it got merged and synced then it should be ok.

**Comment by miclark** [comment]
Hey @matysek, can this issue be closed?
