### ISSUE TITLE
Add sos_commands path entry into sos_archive.py specs file.

### ISSUE THREAD

**Issue by sagaraivale** [RedHatInsights/insights-core#1141]
There are couple of parser which do not have sos_commands entry in 3.x sos_archive.py specs file. 
It is essential for the rules which takes input from sos-reports.

**Comment by csams** [comment]
@sagaraivale thanks for the heads up - which parsers?

**Comment by sagaraivale** [comment]
PR is created for this issue : https://github.com/RedHatInsights/insights-core/pull/1142
@csams  : Kindly review
