### ISSUE TITLE
Missing dependencies in README

### ISSUE THREAD

**Issue by Glutexo** [RedHatInsights/insights-core#1164]
I was trying to clone the project and run the tests. Unfortunately there are not all dependencies listed in the README. Maybe these are obvious, but still it would be helpful to mention them.

To actually run `py.test` you (obviously) need `pip install pytest`. For the tests not to fail with an error, you need `pip install requests` and `pip install pyopenssl` too. I suppose that when these libraries are needed for the tests, they are required by the projects itself as well.

Maybe there is just something missing that would install the dependencies automatically, but just isn’t mentioned in the README?

**Comment by Glutexo** [comment]
Oh, now I can see. `python setup.py install` does the job, right? Maybe it *is* obvious for pythonists, but I‘d still list it in README.

**Comment by csams** [comment]
In python we normally work in virtual environments to keep package installations scoped to a given project. `virtualenv . && . bin/activate && pip install -e .[develop]` in the repo directory will get you going in python 2. `python3 -m venv . && . bin/activate && pip install -e .[develop]` will do it in python 3. We'll update the README to reflect. Thanks!

**Comment by Glutexo** [comment]
Thanks for your response!

`pip install -e .[develop]` didn’t work for me. Bare `pip install -e .` did. These are mentioned in the README already. These did not satisfy the dependencies on my machine though. I had to install them manually. Maybe the `setup.py` script would do that for me?

Right after these steps, there is the `py.test` command to run the tests, which didn’t work for me, because of the dependencies.
