### ISSUE TITLE
No spec for docker_image_inspect and docker_container_inspect

### ISSUE THREAD

**Issue by wushiqinlou** [RedHatInsights/insights-core#1197]
Currently, no spec for docker_image_inspect and docker_container_inspect in insights_archive.py. 

And command prefix for `docker_image_inspect` and `docker_container_inspect` are both 
`docker_inspect`, so the items for `docker_image_inspect` and `docker_container_inspect` would be same when added in insights_archive.py.

docker_container_inspect = glob_file("insights_commands/docker_inspect_*")
docker_image_inspect = glob_file("insights_commands/docker_inspect_*")

To fix this issue, add "--type" option in the two commands, then items for them would be different.

**Comment by wushiqinlou** [comment]
PR for insights_archive.py

https://github.com/RedHatInsights/insights-core/pull/119
https://github.com/RedHatInsights/insights-core/pull/1196

**Comment by miclark** [comment]
Both PR's have been closed because they require a pre-command which will not be added to the `uploader.json`.
