### ISSUE TITLE
Issue with simple_command data source in spec_factory

### ISSUE THREAD

**Issue by lhuett** [RedHatInsights/insights-core#1228]
If using 'ps' command with filters the filter grep command is captured in the ps output and matched on. 
This could cause a problem when evaluating matched content in rules.

        if filters:
            command = [shlex.split(cmd)] + [["grep", "-F", filters]]
            raw = ctx.shell_out(command, split=split, keep_rc=keep_rc, timeout=timeout)

**Comment by miclark** [comment]
Changes made in the plugin code instead of insights-core.  We don't want to hide the insights client processes.  So, those parsing the data need to make sure they get the process they need and not the grep.  I.e., they should be more specific in their matching.
