### ISSUE TITLE
Failing tests in master

### ISSUE THREAD

**Issue by Glutexo** [RedHatInsights/insights-core#1231]
Some tests are failing in the current master (https://github.com/RedHatInsights/insights-core/commit/794a241604123ced97f490243946349e43da4117). See https://gist.github.com/Glutexo/d11ea0568e2ef60dad7d82eca682f5fd for _pytest_ output. The failing tests are:

* insights/combiners/tests/test_httpd_conf.py::test_shadowing
* insights/tests/test_text_file_provider.py::test_command_not_found
* insights/tests/test_text_file_provider.py::test_no_such_file

**Comment by Glutexo** [comment]
I am not sure whether this is true for [current master](
https://github.com/RedHatInsights/insights-core/commit/3c3fb5a0ade8839a0217db014c450a8226c2f76d). It might be worth checking.

**Comment by miclark** [comment]
Master seems to be fine, and we've had multiple releases, so closing.
