### ISSUE TITLE
Run Flake8 lint on RHEL6

### ISSUE THREAD

**Issue by Glutexo** [RedHatInsights/insights-core#1262]
Currently, flake8 is run only on RHEL7 and 8 and not on RHEL6. According to [the documentation](http://flake8.pycqa.org/en/latest/#installation) it is necessary to run flake8 with the exact Python version that is used. Thus to be sure that the syntax is ok even for the older Python version, we have to run in to RHEL6 too.

Tackled in #1251.

**Comment by sourabhtk37** [comment]
Close as complete.

**Comment by Glutexo** [comment]
Are you sure? Jenkinsfile on current _master_ doesn’t run `flake8` for the RHEL6 stage. https://github.com/RedHatInsights/insights-core/blob/561841414573e9cfce9b3632fb0c1528630c5f14/Jenkinsfile#L12

**Comment by sourabhtk37** [comment]
@Glutexo My bad. Should I do a PR?

**Comment by Glutexo** [comment]
Not necessary, it’ll be just a one-liner, so I’ll do it right away. But thanks!

**Comment by Glutexo** [comment]
There is a new PR for this: #1452
