### ISSUE TITLE
Wrong comparison method is used in get_localport and get_peerport of SsTULPN parser  

### ISSUE THREAD

**Issue by vishwanathjadhav** [RedHatInsights/insights-core#1281]
Wrong comparison method is used in get_localport and get_peerport of SsTULPN parser, when port='22' and value of l["Local-Address-Port"]='22450'  then '22 ' is present in l["Local-Address-Port"]. which leads to the wrong conclusion.

**Comment by xiangce** [comment]
Resolved in #1281
