### ISSUE TITLE
httpd_conf parser creating list of objects

### ISSUE THREAD

**Issue by ritwik12** [RedHatInsights/insights-core#1288]
In some cases where we have multiple files inside ``/etc/httpd/conf/httpd.conf`` and ``/etc/httpd/conf.d/*``
httpd_conf is not anymore  an object in those cases, instead it is a list of objects. So here things like    

https://github.com/RedHatInsights/insights-core/blob/e58927cb7ee46382cacfd7af0ca2c56cbf1e35e9/insights/parsers/httpd_conf.py#L69

is not applicable. Here, we need to access the correct object for the desired file and then access ``data`` dictionary. Which becomes -

```  httpd_conf[i].data[('IfModule','prefork.c')]['StartServers'][0].value```
Where "i" is the value of index in the list of object, it depends on the file we want to access.

I guess we need to correct this or update parser docs accordingly.

**Comment by xiangce** [comment]
Hi @ritwik12, currently we can only add all the parsed results of the specs marked with "multi_output=True" in `insights/specs/__init__.py` to a list, and then access them via the `index`.

To resolve this problem, for example, there is a combiner for httpd_conf (`insights/combiners/httpd_conf.py`) to re-arrange all the parsed `HttpdConf` with their source files.

HTH,

**Comment by ritwik12** [comment]
@xiangce Thanks for the help
