### ISSUE TITLE
Quotes and doublequotes break configtree parser

### ISSUE THREAD

**Issue by jsvob** [RedHatInsights/insights-core#1300]
So far tested only with HttpdConfTree (not with other configtree parsers&combiners).

Quotes and doublequotes make the parser crash.

```
CustomLog logs/ssl_request_log \
"%t %h %{SSL_PROTOCOL}x %{SSL_CIPHER}x \"%r\" %b"
```

More context is in https://github.com/RedHatInsights/insights-core/pull/1294/files

In a few minutes I will submit a new PR with a test that shows the bug.

EDIT: Corrected the code to include backslashes I previously mistakenly stripped out.

**Comment by csams** [comment]
Fixed in https://github.com/RedHatInsights/insights-core/pull/1302. Reopen if you still see the issue.
