### ISSUE TITLE
Add xfs_info datasource to default.py

### ISSUE THREAD

**Issue by csams** [RedHatInsights/insights-core#1303]
An xfs_info datasource exists in `sos_archive.py`. Should one exist in `default.py`, and how should it be implemented if so?

**Comment by ritwik12** [comment]
@csams I can see xfs_info already present [here](https://github.com/RedHatInsights/insights-core/blob/9ece3f37358987ed6d245585e065237aedcce4cc/insights/specs/default.py#L713) in default.py. Am I getting confused with something here?

**Comment by csams** [comment]
Hey @ritwik12, yep, it looks like that was added back in September. It's an interesting issue because it's the first case where a datasource depends on a parser. That'll have implications for other things soon, but we can open separate issues as they come up. Thanks!

Fixed in 4f07378d0

**Comment by ritwik12** [comment]
Fixed in #1446

**Comment by ritwik12** [comment]
@csams That looks great, your welcome.
