### ISSUE TITLE
Key error in spec.httpd_conf

### ISSUE THREAD

**Issue by ritwik12** [RedHatInsights/insights-core#1308]
I am writing tests for on of my rules, I am using <b>HttpdConfAll</b> from ```combiners.httpd_conf``` 
as suggested in #1288. But it is giving me Keyerrors as shown:

![screenshot from 2018-07-31 12-31-01](https://user-images.githubusercontent.com/20038775/43443124-9b0ef196-94bd-11e8-9366-56f505f04d50.png)

It will be a great help if you can tell me what's the issue.

**Comment by csams** [comment]
@ritwik12 I've reached out internally.

**Comment by ritwik12** [comment]
Thanks !! @csams
