### ISSUE TITLE
About the parser 'pcs_status', the spec of it does include the full correct file path

### ISSUE THREAD

**Issue by crackcodecamp** [RedHatInsights/insights-core#1315]
For most recent sosreport, the file path would be 'sos_commands/pacemaker/pcs_status' (for example: sosreport-overcloud-controller-0-20180703073332/sos_commands/pacemaker/pcs_status), so this need to be fixed first with adding the path to the sos_archive in insights-core repo.

insights/specs/sos_archive.py:
    pcs_status = simple_file("sos_commands/cluster/pcs_status")
                        ---> this path is for old rhel version

insights/specs/sos_archive.py:
    pcs_status = simple_file("sos_commands/pacemaker/pcs_status")
                        ---> this path is for New rhel version

**Comment by bfahr** [comment]
PR #1317 has been merged with master and 3.0 branches.
