### ISSUE TITLE
Get 100% test coverage of insights/core/__init__.py

### ISSUE THREAD

**Issue by PaulWay** [RedHatInsights/insights-core#139]
At the moment the stats are:

```
Name                           Stmts   Miss Branch BrPart  Cover   Missing
--------------------------------------------------------------------------
insights/core/__init__.py        330     28    106      9    90%   44, 57-60, 296, 333-334, 400, 415-418, 967, 970-975, 978, 981-991, 41->44, 42->44, 52->51, 62->51, 295->296, 385->exit, 399->400, 915->878, 960->exit
```

Items to do:

* `get_module_names()` never hits return False in `name_filter()`.
* `get_module_names()` should check what happens when walk_packages sets ispkg to True.  What does that mean?
* `get_module_names()` should check what happens when `name_filter()` returns False.
* `get_module_names()` should test AttributeError handling.
* `Scannable` should test registering two scanners with the same name.
* `Scannable` should test `__contains__()` method.
* `AlternativesOutput` should test handling of non-matched lines past "Current best version is".
* `Scannable` should test `parse()` method - and parsers should use it.
* `LogFileOuptut` should test registering two scanners with the same name.
* `LogFileOutput` should test `token_scan()` method.
* `ErrorCollector` class needs to be thoroughly tested (967-991)

**Comment by PaulWay** [comment]
https://github.com/RedHatInsights/insights-core/pull/141 solves the ErrorCollector problems:

```
Name                           Stmts   Miss Branch BrPart  Cover   Missing
--------------------------------------------------------------------------
insights/core/__init__.py        305     10    100      8    95%   43, 56-59, 295, 332-333, 399, 414-417, 40->43, 41->43, 51->50, 61->50, 294->295, 384->exit, 398->399, 914->877
```

**Comment by PaulWay** [comment]
Scannable class tests in https://github.com/RedHatInsights/insights-core/pull/144 :
```
Name                           Stmts   Miss Branch BrPart  Cover   Missing
--------------------------------------------------------------------------
insights/core/__init__.py        273      7     80      6    96%   41, 54-57, 454, 469-472, 38->41, 39->41, 49->48, 59->48, 439->exit, 453->454
```

**Comment by PaulWay** [comment]
Waiting on @csams for work on possibly eliminating `get_module_names`.
Waiting on `LogFileOutput` changes in https://github.com/RedHatInsights/insights-core/pull/118 and https://github.com/RedHatInsights/insights-core/pull/119 to complete its testing.
Proposal to move AlternativesOutput around in https://github.com/RedHatInsights/insights-core/issues/140

**Comment by PaulWay** [comment]
Now that #118 and#119 are passed, https://github.com/RedHatInsights/insights-core/pull/219 finishes the rest of the testing in LogFileOutput.

**Comment by jhjaggars** [comment]
@PaulWay ready to close this one?

**Comment by PaulWay** [comment]
Looks good to me now - thanks @jhjaggars, will do!
