### ISSUE TITLE
Mention unsupported docs building on Python 2.6

### ISSUE THREAD

**Issue by Glutexo** [RedHatInsights/insights-core#1391]
Wherever in the documentation is mentioned how to build the documentation (`sphinx-build`), it would be good to mention that this is not possible on Python 2.6. That‘s because the library used (
[nbsphinx](https://pypi.org/project/nbsphinx/)) doesn’t support this legacy version of Python. Moreover it’d be good to briefly mention this wherever we claim that we support Python 2.6.

Replaces #1373.

**Comment by ritwik12** [comment]
@Glutexo I went through the files mentioning sphinx and found that only conf.py is valid to be mentioned about this. I've also sent a PR (#1541) for that.  In other files I couldn't find a need to specify this. If there is a need to specify this in other files too. Please let me know.

**Comment by ritwik12** [comment]
Solved in #1541 (Maybe partially), @csams @xiangce Please let me know if this issue is solved so that it can be closed.

**Comment by bfahr** [comment]
#1541 partially solves this issue, but there are multiple places in the docs that also need to be updated.

**Comment by bfahr** [comment]
I updated the doc guidelines and the reference on the wiki regarding support of Python 2.6 documentation builds.  I think that is everywhere.

**Comment by Glutexo** [comment]
Cool! Thanks, @ritwik12 and @bfahr for addressing this! I‘ll close the issue as it appears solved now.
