### ISSUE TITLE
Stacked Decorators are Bad

### ISSUE THREAD

**Issue by jhjaggars** [RedHatInsights/insights-core#14]
_From @kylape on May 4, 2017 21:1_

We shouldn't let developers stack insights decorators. Currently, they only work if all specs in a stack are pattern specs or if only one spec in a stack is present, and even then, the expected output is hard to reason about.

Example:

    @mapper('foo')
    @mapper('bar')
    class FooBar(Mapper):
        pass

Here's the current code that attempts to handle the pattern spec case. Note this forces the evaluator to assume all mapper outputs are lists.

    def collect_results(results_dict):
        plugin_output = defaultdict(dict)
        shared_output = {}
        for producer, output in results_dict.iteritems():
            if producer.shared:
                if not producer._reducer:
                    is_pattern = pattern_file(producer.symbolic_names[0])
                    shared_output[producer] = output if is_pattern else output[0]
                else:
                    shared_output[producer] = output
            else:
                plugin = sys.modules[producer.__module__]
                plugin_output[plugin].update(autobox(producer.symbolic_names, output))
        return plugin_output, shared_output

Current stacked mappers:

    (falafel-mark2) [10026 csams@localhost mappers]$ ag '@mapper.*\n@mapper'
    lvm.py
    77:@mapper('pvs')
    78:@mapper('pvs_noheadings')
    141:@mapper('vgs')
    142:@mapper('vgs_noheadings')
    211:@mapper('lvs')
    212:@mapper('lvs_noheadings')

    grub_conf.py
    100:@mapper('grub2.cfg')
    101:@mapper("grub.conf")

    xinetd_conf.py
    99:@mapper("xinetd.conf")
    100:@mapper("xinetd.d")

    limits_conf.py
    43:@mapper("limits.conf")
    44:@mapper("limits.d")
    85:@mapper("limits.conf")
    86:@mapper("limits.d")

    httpd_conf.py
    91:@mapper('httpd.conf', filters=['IncludeOptional'])
    92:@mapper('httpd.conf.d')

    modprobe.py
    5:@mapper('modprobe.conf')
    6:@mapper('modprobe.d')

`pvs`, `vgs`, and `lvs` work, but only because of the `NoneGroup` hack. `grub` works because both versions are simple file specs and neither should show up at the same time.  `httpd_conf` works because its `httpd.conf` spec was changed to a pattern file spec.  `xinetd`, `limits_conf`, and `modprobe` are currently broken.

_Copied from original issue: RedHatInsights/falafel#190_

**Comment by jhjaggars** [comment]
_From @PaulWay on May 9, 2017 5:10_

OK, two questions:

Firstly, what about merging these into one spec which gathers all the related files (for xinetd, httpd, modprobe and limits):

In ``specs.py``:
```
    "modprobe_files"            : All(
                                    SimpleFileSpec("etc/modprobe.conf"),
                                    PatternSpec(r"etc/modprobe.d/.*\.conf"),
                                ),
```

Then the mapper would simply do:

```
@mapper('modprobe_files')
class ModProbe(LegacyItemAccess, Mapper):
    ...
```

I agree that stacking decorators has unintended side effects.

Secondly, what if the mapper decorator took a list of spec names:

```
@mapper('modprobe.conf', 'modprobe.d')
class ModProbe(LegacyItemAccess, Mapper):
    ...
```

So that one decorator caught multiple possible matches of the spec to the mapper (class|function).

**Comment by jhjaggars** [comment]
_From @kylape on May 9, 2017 20:23_

Both of those solutions have the same issue as the stacked decorators: you can't mix pattern and simple specs.

**Comment by jhjaggars** [comment]
_From @PaulWay on May 9, 2017 23:17_

OK, then the solution is fairly obvious: only combine PatternSpecs:

```
    "modprobe_files"            : All(
                                    PatternSpec("etc/modprobe.conf"),
                                    PatternSpec(r"etc/modprobe.d/.*\.conf"),
                                ),
```

The second solution above would have the mapper decorator simply return a (flattened) list if it receives more than one spec in its args list, and if there was only one spec in the args list it would do what it does currently (return a single object for a CommandSpec or SimpleFileSpec or First, and a list of objects for PatternSpec and All).

I agree that's still not consistent for the mapper decorator to sometimes return a single object and sometimes return a list.  And we don't really want to break all the rules that use a mapper just because we added a spec to its list.  But the examples you've highlighted - xinetd, httpd_conf, modprobe, limits - are all going to deal with multiple files.  Plugins that use them would all have to handle lists anyway.  I think it's obvious in the semantics there; it'd be good if it was explicit somehow but it's somewhat magical at the moment anyway.

**Comment by jhjaggars** [comment]
_From @PaulWay on May 11, 2017 3:46_

Oh, and here's another thought:

What if there was a way for a single mapper class to receive multiple files (like these examples) as a list of contexts, and then build up a single 'state' of the entire configuration?

That's what xinetd, httpd_conf, modrobe, and limits are doing: storing an overall state in a collection of files.  Then the parsing code would also store the file and line that produced each configuration item, so that a rule could then inform the user which file and which line to change / was wrong.  We don't really want each rule that wants to read this configuration to write a loop (and some already do) that looks through each file for a particular configuration line, and we don't really want every such instance to have to write first a shared mapper to read each file and then a shared reducer that will condense the data into one format.

One simple way to handle this would be an extension of our mapper class structure to implement a MultiFileMapper class:

```
class MultiFileMapper(object):
    """
    Create a single mapper which stores the state of multiple files.
    """
    def __init__(self, context_list):
        for context in context_list:
            context.file_name = os.path.basename(context.path) \
                if context.path is not None else None
            self.parse_context(context)

    def parse_context(self, context):
        """
        Parse and store the data in this context.  Remember to save the
        context's file path and line in any data drawn from the file so that
        reducers can 
        """
        pass
```

And then something like the Modprobe mapper class would look like:

```
@mapper('modprobe-files', multiple=True)
class Modprobe(MultiFileMapper):
    data = defaultdict(dict)
    def parse_context(self, context):
        for line in get_active_lines(context.content):
            for mod_key in ["options", "install"]:
                if line.startswith(mod_key):
                    parts = line.split()
                    self.data[mod_key][parts[1]] = {
                        'value': parts[2:],
                        'file': context.path,
                        'line': line
                    }
```

So the configuration in all the files would be read in one go and parsed into one structure.  The data contains the file and line for each configuration setting that's stored, so that a rule could refer the user to the invalid setting in file '/etc/modprobe.d/blintz.conf' line 'option veeblefetzer disagled'.

How does that sound?

**Comment by jhjaggars** [comment]
_From @kylape on May 23, 2017 22:32_

Hey @PaulWay, sorry for the delayed response here.

Just to make sure we're on the same page:  If a symbolic name is a `PatternFileSpec` or a `CommandSpec` with a `pre_command`, then rules should expect the value of a mapper in the `shared` dict to always be a list.  So a valid workaround is to define `modprobe_files` as you did above, but it would always create a list of mappers, never a single, unwrapped mapper output.

> We don't really want each rule that wants to read this configuration to write a loop (and some already do) that looks through each file for a particular configuration line

Agree.

> and we don't really want every such instance to have to write first a shared mapper to read each file and then a shared reducer that will condense the data into one format.

This actually seems much more reasonable to me.  It's a one-time effort to get the shared reducer written, rather than "reinventing the wheel" when a rule tries to loop over all the mapper outputs in the appropriate way.

So with that said, I think the functionality your `MultiFileMapper` concept provides is already covered by the shared reducer.  I do agree that it's nice to have the logic that would normally go in a shared reducer combined into one place, I don't think it's worth the added API complexity (both for the user and for the framework implementation).  Shared reducers won't be going away since they still have valid use cases separate from e.g. modprobe.d, so rule devs would still need to understand them in addition to the `MultiFileMapper` concept.

I also think it's worth mentioning the inertia associated with a change like this.  Pattern mappers have worked like this for a very long time, and it's worked well enough AFAICT, so the new concept would have to be quite compelling to warrant rule devs to learn a new concept IMHO.

**Comment by jhjaggars** [comment]
_From @PaulWay on May 25, 2017 0:26_

I agree with your point about shared reducers being able to do this job, but I see the MultiFileMapper idea as 'cutting out the middle man'.  For some things, e.g. services, or GRUB config, we're combining information in different formats, so it makes sense to have a reducer.  But for things like e.g. modprobe, where all the data is in the same format and it's treated by the system as one unified source of information, I don't see a reason to have a separate shared reducer if we could have a single mapper that provided the same information that the shared reducer would.

I don't see the inertia issue as being important, to be honest.  We're not going to rewrite everything to use this new mapper class in one cataclysmic change; if and when it happens it'll be done in the standard process of rule and mapper merge requests and reviews.  We'll still have pattern mappers, because those work for other things (e.g. bond or ifcfg) where the individual file name is important.

(Aside - just in reviewing which specs use PatternSpec it would seem imagemagick_policy already uses this "multiple files by PatternSpec" trick...)

The test I apply in my mind is: "would I ever need to refer to a specific file in this collection of files?"  For things like ifcfg, I can see that there might be a bug or problem that's specific to eth0 or lo or whatever, and the rule would need to find that file (although it'd be nice to do that with a better mechanism than iterating through the list of files :-) ).

But for things like modprobe or limits, I can see very few situations where one file is the sole cause of a problem - because users can put configuration in any named file, and sometimes modify standard configuration files to include custom configuration.  So I can see no real need for a rule to find a specific modprobe configuration file by name.  That says to me that a single mapper for that type of file is the right solution.

Anyway, I don't mind - I can try writing up a shared reducer in the short term.  But I'd prefer a long-term simplification for this style of mapper.

**Comment by jhjaggars** [comment]
_From @PaulWay on May 25, 2017 4:0_

I guess the other side of this coin is: I've tried to understand how the mapper gets eventually evaluated and how one would implement a MultiFileMapper of this type, and I'm a bit stumped.  I'd love core/evaluators.py to be a bit more documented :-)  I'm trying to understand how difficult it would be, as a way of understanding whether that's a good way to solve this problem.  If you can help me with any of that please let me know!

**Comment by jhjaggars** [comment]
_From @PaulWay on May 25, 2017 5:24_

OK, I pushed through my initial confusion and came up with this proposal:

https://github.com/RedHatInsights/falafel/pull/250

Let me know what you think! :-)

**Comment by miclark** [comment]
FYI, original trello card: https://trello.com/c/4wqt0KYo

**Comment by csams** [comment]
This has been resolved in core 3.x with the new datasource system.
