### ISSUE TITLE
Fix command specs containing globs

### ISSUE THREAD

**Issue by csams** [RedHatInsights/insights-core#1413]
For security reasons we don't execute datasources in a shell, so path globbing with commands doesn't work. That means that specs like [this](https://github.com/RedHatInsights/insights-core/blob/master/insights/specs/default.py#L614) are invalid.
```
sysctl_conf_initramfs = simple_command("/bin/lsinitrd /boot/initramfs-*kdump.img -f /etc/sysctl.conf /etc/sysctl.d/*.conf")
```

**Comment by bfahr** [comment]
There are two other specs that also have the same problem.
```
mlx4_port = simple_command("/usr/bin/find /sys/bus/pci/devices/*/mlx4_port[0-9] -print -exec cat {} \;")
md5chk_files = simple_command("/usr/bin/md5sum /dev/null /etc/pki/{product,product-default}/69.pem")
```
