### ISSUE TITLE
No parser for getting number of cpu cores

### ISSUE THREAD

**Issue by ritwik12** [RedHatInsights/insights-core#1422]
There is no parser available as per my knowledge to get cpu cores from [cpuinfo](https://github.com/RedHatInsights/insights-core/blob/master/insights/parsers/cpuinfo.py).

See examples of available parsers:

https://github.com/RedHatInsights/insights-core/blob/a0646d86309c0468b27d0ad955ba1a5a238f5677/insights/parsers/cpuinfo.py#L46

**Comment by lhuett** [comment]
Hi Ritwik,
There is actually a property available in the cpuinfo parser called "core_total" that will give you total number of cores.

**Comment by ritwik12** [comment]
@lhuett  Thanks, can you please give me an example of using it? That'll be helpful.

**Comment by ritwik12** [comment]
@lhuett I can see that it was added free days ago in #1390, I wrote my code before that that's why I was unaware of it. Thanks for adding it.

**Comment by lhuett** [comment]
@ritwik12 I should have mentioned that the addition of the property was fairly recently.
Thanks.
