### ISSUE TITLE
nginx_conf collection incomplete?

### ISSUE THREAD

**Issue by csams** [RedHatInsights/insights-core#1472]
Core (and the current client) doesn't collect any of the nginx configuration files in `conf.d/`, `default.d`, etc. Should those be added?

**Comment by xiangce** [comment]
@wushiqinlou - Please take a look at this issue whenever free.

**Comment by xiangce** [comment]
It's resolved in #1797 and https://github.com/RedHatInsights/insights-core-assets/pull/133/files.
