### ISSUE TITLE
FileListing class has selinux arg that is not used

### ISSUE THREAD

**Issue by bfahr** [RedHatInsights/insights-core#1492]
The `FileListing` signature includes an `selinux` argument that is documented to allow parsing of Selinux info in the file listing.  However, it is not used in the code.  Selinux info is parsed if present in the file listing regardless of this argument.

If it was used, then it would cause a problem with `super` resolution because when used with any mixin class, the mixin class `__init__` would not accept the extra argument.

Since `selinux` is not used it should be removed from the signature of the `FileListing` class.  We should also consider adapters if extra arguments are needed with classes that are used with mixin classes.  See [Raymond Hettinger's article](https://rhettinger.wordpress.com/2011/05/26/super-considered-super/) on `super` usage.

**Comment by csams** [comment]
Closed by https://github.com/RedHatInsights/insights-core/pull/1493
