### ISSUE TITLE
Kerberos KDC log parser for 2.x branch

### ISSUE THREAD

**Issue by xiangce** [RedHatInsights/insights-core#153]
Need a PR to master branch corresponding to #147

**Comment by PaulWay** [comment]
Why do I have two PRs for the 1.x branch when I really want this to be for the master branch?  Let's fix that.

**Comment by PaulWay** [comment]
This is now available as https://github.com/RedHatInsights/insights-core/pull/166

**Comment by xiangce** [comment]
Both #166 and #147 are merged.
