### ISSUE TITLE
Unnecessary Exception raised

### ISSUE THREAD

**Issue by vishwanathjadhav** [RedHatInsights/insights-core#1564]
In bond.py unnecessary exception is raised "Unrecognised bonding mode", no need to raise an exception if mentioned bonding mode is not in the map

**Comment by vishwanathjadhav** [comment]
https://github.com/RedHatInsights/insights-core/pull/1565

**Comment by bfahr** [comment]
The change to remove the exception was reverted and PR #1565 was merged.  @vishwanathjadhav can this issue be closed?  If not please provide a more detailed explanation of why the exception is unnecessary.
