### ISSUE TITLE
GRUB2 on RHEL8 - add support for blscfg

### ISSUE THREAD

**Issue by jsvob** [RedHatInsights/insights-core#1650]
* GRUB2 in RHEL8 is configured in such a way that it uses blscfg and entries in /boot/loader instead of menuentry entries in grub.cfg as is in RHEL7.
* The current grub_conf parser doesn't work with blscfg files.

References:

* https://fedoraproject.org/wiki/Changes/BootLoaderSpecByDefault
* https://www.thegeekdiary.com/modifying-etc-default-grub-rhel-7-v-s-rhel-8/?PageSpeed=noscript

**Comment by psachin** [comment]
I'll take this task

**Comment by xiangce** [comment]
@psachin - have you started working on this issue? If not, I will work on it.

Duplicate issue:  #1972

**Comment by xiangce** [comment]
As discussed in the meeting, I'll take this issue.

**Comment by jsvob** [comment]
It still doesn't work as expected. Steps to reproduce:

1. RHEL8 machine with the default configuration
2. grubby --update-kernel=ALL --args=selinux=0
3. reboot
4. sestatus shows disabled
5. /boot/grub2/grubenv (or the EFI variant on EFI systems) doesn't contain the selinux=0 argument:

```

# GRUB Environment Block
saved_entry=0
kernelopts=root=/dev/mapper/rhel-root ro crashkernel=auto resume=/dev/mapper/rhel-swap rd.lvm.lv=rhel/root rd.lvm.lv=rhel/swap rhgb quiet 
boot_success=0
boot_indeterminate=0
##########################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################

```

6. Only this file (depending on the particular version) contains the argument added by grubby:  `/boot/loader/entries/7b72675be917477dbfea43edd54377ba-4.18.0-80.el8.x86_64.conf`
7. Again, the reason is that insights don't parse blscfg configuration and don't see it.

Thank you

**Comment by xiangce** [comment]
@jsvob - Thanks for checking. I have opened #2041 for this problem too. And I have raised #2043 to fix it by collecting the files under the `/boot/loader/entries/` just like you mentioned above.

Will let you know when the #2043 is merged.

**Comment by jsvob** [comment]
@xiangce thank you!
