### ISSUE TITLE
NTPConfParser class is missing from the documentation

### ISSUE THREAD

**Issue by bfahr** [RedHatInsights/insights-core#167]
@PaulWay the NTPConfParser class is missing from the documentation in PR #109 and I didn't notice until after it was merged. Please update the 1.x branch documentation.  This same error is present in the PR #108 which has not been merged yet.

**Comment by PaulWay** [comment]
Hmmm - it's not supposed to be. It's a base class for NTP_conf and ChronyConf, so they both work the same way. It doesn't have a parser decorator for that reason. I certainly agree that both NTP_conf and ChronyConf need better documentation if they're going to refer to a class that doesn't exist, but I'd rather not mention the base class so as to prevent rule writers thinking they need to use that class.

How about I update the NTP_conf and ChronyConf documentation with a copy of the documentation in NTPConfParser? What's the best way of getting good documentation into the parsers that we want people to use?

**Comment by bfahr** [comment]
@PaulWay I think that until we have a new proposal on the table for how to best present the parsers in the documentation that we have to continue to include all code as we have in the past.  If you want to create a branch and propose a new way to generate the docs then I think that would be the best way to effect change.

**Comment by PaulWay** [comment]
OK.
