### ISSUE TITLE
Failed to get CephVersion from sosreport archives

### ISSUE THREAD

**Issue by xiangce** [RedHatInsights/insights-core#1684]
The "ceph -v" command is not collected by sosreport.
An alternative command could be `sosreport-ceph1-2019-02-15-ylqlcnw/sos_commands/ceph/ceph_report`

Seems, a new parser to parse this `ceph_report` is needed. And then we can combine it with the `CephVersion` to get the CephVersion of the current host from sosreport archives

**Comment by xiangce** [comment]
Seems the `ceph_report` can output the metadata of each node in the whole ceph cluster, it's a nice command for insights to diagnose cluster issues.

**Comment by chenlizhong** [comment]
all ceph commands in sosreport:
            "ceph status",
            "ceph health detail",
            "ceph osd tree",
            "ceph osd stat",
            "ceph osd dump",
            "ceph mon stat",
            "ceph mon dump",
            "ceph df",
            "ceph report",
            "ceph osd df tree",
            "ceph fs dump --format json-pretty",
            "ceph fs ls",
            "ceph pg dump",
            "ceph health detail --format json-pretty",
            "ceph osd crush show-tunables",
            "ceph-disk list"

https://github.com/sosreport/sos/blob/master/sos/plugins/ceph.py

**Comment by miclark** [comment]
@chenlizhong, @xiangce, what's the status of this card? Still something you guys are planning to create?

**Comment by shzhou12** [comment]
The pr to fix this issue is https://github.com/RedHatInsights/insights-core/pull/1973
