### ISSUE TITLE
Add filtering to the result of insights-run

### ISSUE THREAD

**Issue by koalakangaroo** [RedHatInsights/insights-core#1687]
Currently, insights-run displays all the passed|failed result of rules. It is useful to have filtering option to insights-run command that the users can filter out what they are after.

**Comment by xiangce** [comment]
@koalakangaroo - I added an option `-F` to output the `FAIL` items only when being specified.
Please check if the name is OK and if it matches the requirement.

~~~
  -F, --fail-only       Show FAIL results only. Conflict with '-m', will be
                        dropped when using them together
~~~

**Comment by rcernin** [comment]
Thank you works great.

**Comment by xiangce** [comment]
Resolved in https://github.com/RedHatInsights/insights-core/pull/1690
