### ISSUE TITLE
pcs_config parser returns list instead of dict in "Cluster Properties"

### ISSUE THREAD

**Issue by Meiyan89** [RedHatInsights/insights-core#1734]
I want to get the value of stonith-enabled in "Cluster Properties", but I found it returns a list instead of dict. This makes me to write an extra loop convert list to dict. 

++++
def stonith_is_enabled(pacemaker_config):
    cluster_properties = pacemaker_config.get("Cluster Properties")  <===
    cluster_props=dict(map(str, x.split(':')) for x in cluster_properties) <===
    stonith_enable = cluster_props['stonith-enabled']
+++++

Is it possible to make "Cluster Properties" return a dict? 

Best Regards,
Meiyan

**Comment by miclark** [comment]
Since the current interface already returns a list, we don't want to change that behavior.  However, we can add a new attribute, say, `cluster_properties` that provides access to the desired dict.

**Comment by koalakangaroo** [comment]
@Meiyan89 - agreed with @miclark. We prefer not to change the existing behavior in case it is being used in some rules. @xiangce mentioned that we can provide another attribute to provide a dict format. 

@chenlizhong - can you enhance this parser?

**Comment by chenlizhong** [comment]
@koalakangaroo 

OK. Will fix it this week.

**Comment by chenlizhong** [comment]
https://github.com/RedHatInsights/insights-core/pull/1775

**Comment by xiangce** [comment]
resolved in https://github.com/RedHatInsights/insights-core/pull/1775, @Meiyan89 please have a check on the latest `insights-core` and feel free to open issue for any questions. Thanks.
