### ISSUE TITLE
FileListing parser does not correctly handle directory path with dot

### ISSUE THREAD

**Issue by shzhou12** [RedHatInsights/insights-core#1748]
I want to write a parser to parse the output of command `ls -l /var/lib/origin/openshift.local.volumes/pods`. 

The mangled file path is `insights_commands/ls_-l_.var.lib.origin.openshift.local.volumes.pods`.

~~~
╰>mangle '/bin/ls -l /var/lib/origin/openshift.local.volumes/pods'
insights_commands/ls_-l_.var.lib.origin.openshift.local.volumes.pods
~~~

Because there are dots in the directory path, it is hard for the class FileListing to restore the directory path.
Currently, we do it by simply replace dot to slash as the following code in the FileListing class.

~~~
self.first_path = '/' if not fpath else fpath.replace('.', '/').replace('_', ' ')
~~~

As a result, The directory path `/var/lib/origin/openshift.local.volumes/pods` is now recognized as `/var/lib/origin/openshift/local/volumes/pods`·
It is not the correct directory path.

**Comment by shzhou12** [comment]
Is it possible to workaround this issue by testing the new directory path `/var/lib/origin/openshift/local/volumes/pods` as in https://github.com/RedHatInsights/insights-core/pull/1747/files#diff-70e79432f9725b57283958500bdd7806R20

**Comment by miclark** [comment]
Should be be using the `listdir` function from the `spec_factory`?

**Comment by shzhou12** [comment]
@miclark Yes, we can use listdir combine with the new python datasource. I will close this issue.
