### ISSUE TITLE
LsPci needs to be anything but a LogFileOutput class

### ISSUE THREAD

**Issue by PaulWay** [RedHatInsights/insights-core#176]
Should really implement parsing of `lspci` output, and look up by name or ID and so forth.  The use of LogFileOutput introduces unwanted behaviour.  This is probably best implemented as a Scannable.

**Comment by jhjaggars** [comment]
@PaulWay Did you end up doing anything about this?

**Comment by PaulWay** [comment]
Sorry, I'm hoping that other prospective parser writers would look into this.  I've been busy on other things :-)  Just trying to log the issues I see and keep moving.

**Comment by csams** [comment]
lspci supports a machine readable format that's probably worth exploring.

**Comment by miclark** [comment]
Closing due to age.  If someone needs more specific parsing, we should create a new "lspci -vmm" spec/parser at that time.
