### ISSUE TITLE
Do we need ceph_version parser?

### ISSUE THREAD

**Issue by psachin** [RedHatInsights/insights-core#1764]
Using the new `ceph_insights` parser we can pull below information:

```json
  "version": {
    "release": 14,
    "major": 0,
    "full": "ceph version 14.0.0-3517-g5322f99370 (5322f99370d629f6927b9c948522a003fc5da5bb) nautilus (dev)",
    "minor": 0
  },
```

**Comment by psachin** [comment]
@csams @xiangce @mykaul

**Comment by mykaul** [comment]
I needed a combiner, as it is available in multiple files, not all of which are always available. For example, ceph version command was not always collected in sosreport, but ceph status was, and includes the version.

**Comment by xiangce** [comment]
@mykaul++, the combiner is the best solution.

**Comment by xiangce** [comment]
@JoySnow - Would you please to take a look at this issue and make a combiner for `ceph_version` which combines the `ceph_version` parser and `ceph_insights` parser to get the `ceph verison` information?

**Comment by JoySnow** [comment]
@xiangce  Sure, I will take this issue.

**Comment by JoySnow** [comment]
@shzhou12   
I saw that this issue is linked somewhere else internally.  Could you help to update this issue's status?

**Comment by shzhou12** [comment]
@JoySnow Thanks for your reminder, I have submit a PR to fix this issue.

**Comment by shzhou12** [comment]
https://github.com/RedHatInsights/insights-core/pull/1951

**Comment by psachin** [comment]
This is fixed in https://github.com/RedHatInsights/insights-core/pull/1951
