### ISSUE TITLE
No parser for /sos_commands/ceph/ceph_osd_tree in sosreport 

### ISSUE THREAD

**Issue by Meiyan89** [RedHatInsights/insights-core#1776]
Hi team,

I want to write a rule to check if any osd in down status, but I didn't find any parser for /sos_commands/ceph/ceph_osd_tree in sosreport. Any chance to provide this parser? 

Here is the example for ceph_osd_tree in sosreport:
```
ID WEIGHT  TYPE NAME                        UP/DOWN REWEIGHT PRIMARY-AFFINITY 
-1 6.72040 root default                                                       
-2 2.45160     host overcloud-cephstorage-1                                   
 0 0.81720         osd.0                         up  1.00000          1.00000 
 3 0.81720         osd.3                         up  1.00000          1.00000 
 6 0.81720         osd.6                         up  1.00000          1.00000 
-3 1.81720     host overcloud-cephstorage-2                                   
 4 1.00000         osd.4                       down        0          1.00000 
 7 0.81720         osd.7                         up  1.00000          1.00000 
-4 2.45160     host overcloud-cephstorage-0                                   
 1 0.81720         osd.1                         up  1.00000          1.00000 
 5 0.81720         osd.5                         up  1.00000          1.00000 
 8 0.81720         osd.8                         up  1.00000          1.00000 
```

Best Regards,
Meiyan

**Comment by csams** [comment]
Hey @Meiyan89 Thanks for opening the issue! [The `ceph insights` command also provides this data as a subset of its output](https://github.com/RedHatInsights/insights-core/blob/master/insights/parsers/tests/test_ceph_insights.py#L427). My thoughts:

1. We try to collect this data by running `ceph osd tree` from insights if `ceph insights` isn't available. The parser could be written to handle both the data provided by the command with insights and from sos report.
2. We write a combiner that accepts the ceph insights parser and the proposed parser for `ceph osd tree`  and provides a consistent model for that subset of data regardless of how it is obtained.

**Comment by xiangce** [comment]
@Meiyan89 Thanks for the nomination, @csams - Thanks for the suggestion, it makes sense to me.

@shzhou12 - Would you please to take a look at it and make the parser and combiner?

**Comment by koalakangaroo** [comment]
Now we have a parser for this spec: 
```
ceph_osd_tree = simple_command("/usr/bin/ceph osd tree -f json-pretty")
```
The difference to the file in sosreport is insights-client runs this command with json-pretty parameter and the output is in json format.
Furthermore, as @csams mentioned, "ceph osd tree" is also part of the "ceph insights" command but the latter is not available in the current Red Hat Ceph product. 
Here is the resolution:
1. add a spec for sosreport
2. create a new parser for ceph_osd_tree
3. create a combiner to accepts the three parsers

**Comment by koalakangaroo** [comment]
@shzhou12 - if the resolution above makes sense to you, please implement it.

**Comment by shzhou12** [comment]
@koalakangaroo Thanks for your suggestion, I will implement the parser and combiner.

**Comment by noahdesu** [comment]
Hey everyone. I'm taking a look at the correspondence between the ceph osd tree information from CLI and that from JSON. I'll drop a note here soon when I have an update.

**Comment by shzhou12** [comment]
@noahdesu  I have implement a parser for the CLI command and a corresponding combiner for all the ceph osd tree data source. It is now under review.

**Comment by shzhou12** [comment]
https://github.com/RedHatInsights/insights-core/pull/1806

**Comment by noahdesu** [comment]
Hey @shzhou12 I would recommend consuming the data from the existing ceph data source. It's purpose is to remain stable compared to the CLI. I know there are a few questions about that data source that I'm still resolving. Did you find anything missing from the existing data source that was insufficient for your needs?

**Comment by shzhou12** [comment]
@noahdesu Hi, the existing ceph data source could provide sufficient information. This issue is irrelevant to the information but to compatible with SOSreport result. Insights-core is able to parse data collected by SOSreport. SOSreport get the osd tree information by run the CLI command, you can check this in [sosreport source code](https://github.com/sosreport/sos/blob/dfed1abf3cac691cfc669bbf4e07e58e2e637776/sos/plugins/ceph.py#L55). So, we need to implement another parser to parse the plain text result and a combiner return the best information to insights-core users.

**Comment by noahdesu** [comment]
Ah, thanks for the explanation. Then perhaps (and maybe this is what @csams was alluding to) we transform the sosreport data into the same JSON structure produced by the existing collection. This would be nice because it would then allow us to easily go change the sosreport collection without much disturbance.

**Comment by shzhou12** [comment]
This issue has been fixed in https://github.com/RedHatInsights/insights-core/pull/1806.
