### ISSUE TITLE
[RFE] Abrt DUPHASH integration for backtraces

### ISSUE THREAD

**Issue by mykaul** [RedHatInsights/insights-core#1785]
Utilize the DUPHASH capability of abrt[1] (or [2], for regular backtraces, btw!) to find out matches.

[1] https://github.com/abrt/abrt/blob/master/src/plugins/abrt-action-analyze-oops.c
[2] https://github.com/abrt/abrt/blob/a2a2516d77291e76063eae5e07c4c44428b7b2cb/src/plugins/abrt-action-analyze-backtrace.c

**Comment by ernestask** [comment]
Hi, ABRT dev here. Could you go into a bit more detail about your use case here?

**Comment by mykaul** [comment]
1. An sosreport arrives is attached to a case.
2. Insights rules scan it (its journal, for example).
3. In case of an oops, a backtrace, a duphash is calculated, and checked against known ones.

**Comment by mykaul** [comment]
@ernestask - thoughts on the above?

**Comment by ernestask** [comment]
Can’t speak on behalf of Insights devs, but that doesn’t sound like something that would fit. Most rules focus on actionable items, like fixing improper configuration or updating a package.

**Comment by mykaul** [comment]
My question was more into the integration part  - is, in your opinion, it is feasible to integrate the ABRT DUPHASH functionality into Insights, so it'll be able to analyse backtraces (in sosreport) so we can do a search for existing issues?

**Comment by miclark** [comment]
Closing as this doesn't seem like a core feature over a particular application (that uses core, possibly.)
