### ISSUE TITLE
Issue in insights_commands/ethtool_-k_* and other ethtool spec

### ISSUE THREAD

**Issue by rasrivas-redhat** [RedHatInsights/insights-core#1791]
It seems there is a bug in spec creation for `insights_commands/ethtool_-k_*` and other related specs related to **ethtool** command when a **VLAN connection** configured on the host. The spec which is currently created is `ethtool_-i_bond0.123_bond0` which should be actually `ethtool_-i_bond0.123` and due to which we are getting `Cannot get device feature names: No such device` when we open `insights_commands/ethtool_-k_ethtool_-k_bond0.123_bond0` logically this device does not exist on this host. It looks that the interface name is referred from `/sys/class/net` and then referred to ethtool command, but for VLAN interface seems it fails to refer the correct interface name. 

Below is an example for reference.

```
[root@rhel7-box vagrant]# ls insights-rhel7-box-20190403111343/sys/class/net/
bond0/     bond0.123/ enp0s3/    enp0s8/    enp0s9/    lo/
``` 

```
[root@rhel7-box vagrant]# ls insights-rhel7-box-20190403111343/insights_commands/ethtool_-k_
ethtool_-k_bond0            ethtool_-k_bond0.123_bond0  ethtool_-k_enp0s3           ethtool_-k_enp0s8           ethtool_-k_enp0s9
```

**Comment by miclark** [comment]
@gravitypriest, I think this is a client issue, let us know if that's not correct.

**Comment by gravitypriest** [comment]
It sort of is, I remember seeing emails about this issue before.

The pre-command we use for getting the devices for the ethtool commands is `/sbin/ip -o link | awk -…nk\\/ether/ {print $2}'`, but it looks like it's not providing the expected device name in this case. Perhaps we should consider altering the command in uploader.json.

**Comment by csams** [comment]
@gravitypriest I'm not sure if this is related, but for a while we've been seeing exceptions like

```
insights.parsers.ParseException: ('ethtool: bad command line argument for ethtool', ['ethtool: bad command line argument(s)', 'For more information run ethtool -h'])
```
and
```
insights.parsers.ParseException: bad line: For more information run ethtool -h
```

in about ~90% of archives.

**Comment by gravitypriest** [comment]
@csams any logged examples of invalid commands getting made?
