### ISSUE TITLE
`DmesgLineList` parser cannot handle wrapped dmesg output

### ISSUE THREAD

**Issue by skontar** [RedHatInsights/insights-core#1792]
`dmesg` command uses circular buffer and can wrap. 

`DmesgLineList` parser should be replaced with a combiner, which tries to parse `/var/log/dmesg` first if available, and parse output from `dmesg` command as a fallback only.

Indication of wrapped `dmesg` command can be also done when simply looking for string `Linux.version`.

**Comment by wushiqinlou** [comment]
@skontar - If we choose to check `/var/log/dmesg` first, following scenario may hit false hit:

1, there is an issue A which involves log B in `dmesg` and `/var/log/dmesg`.

2, Customer fixed issue A, and log B gets covered in `dmesg` after a while.

3, In this time, insights would still return error_key if we check `/var/log/dmesg` first. 

On my opinion, `dmesg` is newest info and should be parsed first, please correct me if I am wrong

**Comment by skontar** [comment]
Yes, you are right. I was under the impression that `dmesg` messages are being saved in `/var/log/dmesg` continually but it seems that they are only copied after boot finishes. Either `dmesg` command or `/var/log/dmesg` is not useful under all situations so the combiner should store both and have useful interfaces to help you pick correct source. 

We are tracking it under https://bugzilla.redhat.com/show_bug.cgi?id=1703084 and already started working on it. 

Thanks for sharing your concerns.

**Comment by miclark** [comment]
Hey @skontar, any status update on this?

**Comment by skontar** [comment]
@miclark no. Our intern who is assigned is our for exams and we do not really have it high on our priority list. Is anyone else interested in it? If so we can set the priority higher.

**Comment by bfahr** [comment]
@skontar @jobselko is this issue fixed by PR #2040 ?

**Comment by skontar** [comment]
Yes, I think so.
