### ISSUE TITLE
`modinfo` on all loaded modules

### ISSUE THREAD

**Issue by skontar** [RedHatInsights/insights-core#1793]
If there is a way how to call `modinfo` on all loaded modules, it should be implemented.

The detection script uses the following construction to get all non-retpoline modules:
`lsmod | awk '{ if (NR > 1 && system("modinfo " $1 " | grep -q -e \"retpoline:[ ]*Y\"")) print $1 }'`

Storing `modinfo` for every module returned from `lsmod` would be preferable.

**Comment by miclark** [comment]
This should be covered when we move to "core 3" collection.

**Comment by jsvob** [comment]
@miclark Is there a way I can maybe try to help out with this? I already know the basics of creating a new traditional spec, a new parser, a new combiner :) But this is new, I know nothing about it, and in the future, I will need to know how to develop core 3 collection anyway, so why not learn it now:)

**Comment by jsvob** [comment]
FTR, I've received guidance on Slack. Core collection will not happen for some time so this is not urgent.

**Comment by jsvob** [comment]
@skontar  So IIUC, once core3 collection is in production, we start to get modinfo data.

**Comment by skontar** [comment]
@jsvob 🏅

**Comment by bfahr** [comment]
@skontar @jsvob was this satisified by #2039 ?

**Comment by jsvob** [comment]
@bfahr yes
