### ISSUE TITLE
Local routes are filtered in the `RouteDevices` parser

### ISSUE THREAD

**Issue by vishwanathjadhav** [RedHatInsights/insights-core#1803]
Need to enhance the `RouteDevices` parser for the local routing table. Currently, local routes are filtered in the parser's code logic. If the machine has IP addresses on a network interface, there will be a route to each locally hosted IP in the local routing table. The local routing table is important for one of the insights-rule, hence enhancing the parser.

Parser PR: https://github.com/RedHatInsights/insights-core/pull/1799

**Comment by xiangce** [comment]
resolved in https://github.com/RedHatInsights/insights-core/pull/1799
