### ISSUE TITLE
Check of the IGNORE_TYPES is not correct

### ISSUE THREAD

**Issue by xiangce** [RedHatInsights/insights-core#1818]
https://github.com/RedHatInsights/insights-core/pull/1799/files#diff-ae6e6bc9b6b77e1c6da1fea15c3dfb99R335

https://github.com/RedHatInsights/insights-core/blob/master/insights/parsers/tests/test_ip.py#L335

`local` is moved to the `SAVED_TYPES`, but this check is still OK. That's incorrect

**Comment by miclark** [comment]
Fix has been merged, closing.
