### ISSUE TITLE
New parser for PsAlxww

### ISSUE THREAD

**Issue by dwolfATL** [RedHatInsights/insights-core#1833]
New parser for PsAlxww added to https://github.com/RedHatInsights/insights-core/blob/master/insights/parsers/ps.py and supporting files. This will allow for parsing output for ```ps -alxww```.

The parser should look quite similar to PsEf since the command output is similar. These options should be changed for the new parser: 

```
command_name = "COMMAND"
user_name = "F"
max_splits = 12
```

Here is sample output for ```ps -alxww```:

| F  | UID | PID | PPID | PRI | NI | VSZ | RSS | WCHAN | STAT | TTY | TIME | COMMAND
| :-- | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | --: |
| 4 | 0 | 1 | 0 | 20 | 0 | 193704 | 6952 | ep_pol | Ss | ? | 0:10 | /usr/lib/systemd/systemd |
| 1 | 0 | 2 | 0 | 20 | 0 | 0 | 0 | kthrea | S | ? | 0:00 | [kthreadd]
| 1 | 0 | 3 | 2 | 20 | 0 | 0 | 0 | smpboo | S | ? | 0:00 | [ksoftirqd/0] |

**Comment by bfahr** [comment]
@dwolfATL let me know that this is for sosreports only.
