### ISSUE TITLE
The default comparison method of InstalledRpm should only for packages from "Red Hat"

### ISSUE THREAD

**Issue by xiangce** [RedHatInsights/insights-core#1836]
We got the following result from one archive:
~~~
{
  "fixed_liberasurecode": "liberasurecode-1.2.0-2.el7ost",
  "liberasurecode": "liberasurecode-1.1.0-3.ibm.el7",
  "node_type": "Controller",
  "rhosp_version": 10,
  "type": "rule"
}
~~~

The customer has installed the package `"liberasurecode-1.1.0-3.ibm.el7"` which is not from `Red Hat`. It's not good to report the rule to the customer in the case that CU has used customed packages.

Better make sure the default comparison method of  InstalledRpm is for packages from "Red Hat".
[Update] - ^ Do not want to break the existing rules

We could add another new comparison method to compare packages from all kinds of sources.

**Comment by xiangce** [comment]
This is the comparison of the `release part`: https://github.com/RedHatInsights/insights-core/blob/master/insights/parsers/installed_rpms.py#L586

**Comment by csams** [comment]
Maybe look at vendor, buildhost, or release, as a heuristic. Be sure we don't break the parser when it handles the rpm file in sosreport.
