### ISSUE TITLE
 Specs.software_collections_list: Option `-l` is changed to 'list-collections' in RHEL8

### ISSUE THREAD

**Issue by xiangce** [RedHatInsights/insights-core#1870]
In RHEL6/7

~~~
# scl --list
devtoolset-7
httpd24
~~~
In RHEL8

~~~
# scl --list
You use deprecated syntax "-l|--list", use "list-collections" instead.
# scl list-collections
 <-- Get nothing
~~~
As per [rhel8-using_application_stream](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8-beta/html-single/using_application_stream/index#distribution-of-content-in-rhel8_using-appstream), seems the RHSCL will not be used in RHEL8. 

When confirming that it's indeed not used in RHEL8, this issue could be closed.

**Comment by wushiqinlou** [comment]
@xiangce - According to my investigation, there is no RHSCL in RHEL8 currently, we can wait when RHEL8 get released officially, then have a further check.

**Comment by psachin** [comment]
@xiangce @wushiqinlou I got similar output as mentioned in the description on RHEL 8(GA). 

Although `scl-utils` package is available but `rhscl` repo is not available

```
# yum whatprovides */scl
Updating Subscription Management repositories.
Last metadata expiration check: 1:07:16 ago on Tue 28 May 2019 02:17:04 PM IST.
scl-utils-1:2.0.2-7.el8.x86_64 : Utilities for alternative packaging
Repo        : XXXXX-AppStream
Matched from:
Filename    : /etc/bash_completion.d/scl
Matched from:
Filename    : /usr/bin/scl

scl-utils-1:2.0.2-7.el8.x86_64 : Utilities for alternative packaging
Repo        : rhel-8-for-x86_64-appstream-rpms
Matched from:
Filename    : /etc/bash_completion.d/scl
Matched from:
Filename    : /usr/bin/scl

# cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.0 (Ootpa)

# subscription-manager repos --list | grep rhscl
<NO OUTPUT>
```

RHSCL is deprecated in favor of AppStream
