### ISSUE TITLE
wrong specs for heat api log 

### ISSUE THREAD

**Issue by asyedham** [RedHatInsights/insights-core#1886]
when we check the heat-api.log in infrared setup for OSP13 it shows error info like follow:
[heat-admin@controller-0 ~]$ tail -f /var/log/containers/heat/heat-api.log
tail: cannot open ‘/var/log/containers/heat/heat-api.log’ for reading: No such file or directory
tail: no files remaining
``
Similar issue can also be observed in devstack . The file path is '/var/log/%APACHE_NAME%/heat_api.log' which specified in apache-heat-api.template is https://github.com/openstack/heat/blob/master/devstack/lib/heat#L302

**Comment by koalakangaroo** [comment]
@ppandey-redhat @psachin - can you check this issue?

**Comment by psachin** [comment]
@asyedham 

1. You are checking heat on the controller node. AFAIK, the heat related processes and logs are expected on the OpenStack undercloud node.[1] 

2. I don't find any reference docs to validate that the file name was changed on RHOSP 13(`/var/log/heat/heat-api.log` to `/var/log/heat/heat_api.log`). Do you see the path as `/var/log/heat/heat_api.log` on your Controller node?

If your concern is that the logs are not collected by the insights-client, the reason will be **1.** as well as what explained by @xiangce in the [comment](https://github.com/RedHatInsights/insights-core/pull/1887#pullrequestreview-233768078)


[1] https://github.com/openstack/heat/blob/master/doc/source/configuration/logs.rst

**Comment by venkataanil** [comment]
I have a OSP 14 setup in which undercloud openstack services are deployed using containers. Here I can see heat api log as heat_api.log and not as heat-api.log. May be for container based deployments, change the log path to /var/log/containers/heat/heat_api.log ?

(undercloud) [stack@undercloud-0 ~]$ ls /var/log/containers/heat/
heat_api_cfn.log  heat_api_cfn.log.1  heat_api_cfn.log.2.gz  heat_api.log  heat_api.log.1  heat_api.log.2.gz  heat_api.log.3.gz  heat_api.log.4.gz  heat-engine.log  heat-engine.log.1  heat-engine.log.2.gz

**Comment by asyedham** [comment]
@psachin [2] yeah we can also check the heat_api.log on controller. I have checked it on my OSP 13 setup.
 [heat-admin@controller-0 ~]$ vi /var/log/containers/heat/heat_api.log
2019-05-06 00:01:04.562 19 DEBUG heat.api.middleware.version_negotiation [-] Processing request: GET / Accept: */* process_request /usr/lib/python2.7/site-packages/heat/api/middleware/version_negotiation.py:50
2019-05-06 00:01:34.915 22 DEBUG heat.api.middleware.version_negotiation [-] Processing request: GET / Accept: */* process_request /usr/lib/python2.7/site-packages/heat/api/middleware/version_negotiation.py:50
2019-05-06 00:02:05.244 20 DEBUG heat.api.middleware.version_negotiation [-] Processing request: GET / Accept: */* process_request /usr/lib/python2.7/site-packages/heat/api/middleware/version_negotiation.py:50
2019-05-06 00:02:35.662 19 DEBUG heat.api.middleware.version_negotiation [-] Processing request: GET / Accept: */* process_request /usr/lib/python2.7/site-packages/heat/api/middleware/version_negotiation.py:50
I have raised a jira request for the specs change as suggested my @xiangce to add this spec change

**Comment by psachin** [comment]
@venkataanil, @asyedham In that case we need to add an item in https://github.com/RedHatInsights/insights-core/blob/master/insights/specs/default.py#L308. Needless to say, the collection will only work when the https://github.com/RedHatInsights/insights-core-assets/blob/master/uploader.json has the entries.

**Comment by psachin** [comment]
This is fixed by https://github.com/RedHatInsights/insights-core/pull/1887. The specs are added in https://github.com/RedHatInsights/insights-core-assets/pull/167
