### ISSUE TITLE
issue on parsing line endswith "*" in krb5.py

### ISSUE THREAD

**Issue by wushiqinlou** [RedHatInsights/insights-core#1911]
Placing a * at the end of a line indicates that this is the final value for the tag. This means that neither the remainder of this configuration file nor any other configuration file will be checked for any other values for this tag. While code in krb5.py chooses to skip the rest after *, which is wrong.

**Comment by miclark** [comment]
Hey @wushiqinlou, could you provide some examples of the text that is being parsed incorrectly?

**Comment by bfahr** [comment]
@wushiqinlou @vishwanathjadhav how is this issue impacted by #1869 ?

**Comment by wushiqinlou** [comment]
@miclark - In current test, there is "*" after line 73, current logic will ignore both line 73 and line 74, so there is no option "admin_server" in the result. However, The correct logic is that it can ignore line 73, and should not ignore line 74. @bfahr - This issue has no relationship with 1869, I will try to fix this issue about 1869 got merged.

**Comment by miclark** [comment]
@wushiqinlou, any update on this issue?

**Comment by wushiqinlou** [comment]
@miclark - Try to finish it these two weeks.

**Comment by wushiqinlou** [comment]
Fix in https://github.com/RedHatInsights/insights-core/pull/1967
