### ISSUE TITLE
Sync specs in sos_archive.py

### ISSUE THREAD

**Issue by wushiqinlou** [RedHatInsights/insights-core#1950]
Due to some commands or file paths got changed in different package `sos` versions, relevant specs in sos_archive.py may hit miss or error. This issue is used to track this fix, will close after fixing all the issue specs.

**Comment by wushiqinlou** [comment]
First Part: https://github.com/RedHatInsights/insights-core/pull/1949

**Comment by xiangce** [comment]
Second Part: #1953

**Comment by wushiqinlou** [comment]
Third Part: https://github.com/RedHatInsights/insights-core/pull/1959

**Comment by wushiqinlou** [comment]
Fourth part: https://github.com/RedHatInsights/insights-core/pull/1960

**Comment by wushiqinlou** [comment]
Fifth part: https://github.com/RedHatInsights/insights-core/pull/1962
