### ISSUE TITLE
Please add parser: ovs_vsctl_list_interface for sosreport

### ISSUE THREAD

**Issue by zerodayz** [RedHatInsights/insights-core#1977]
Please add new parser: ovs_vsctl_list_interface for sosreport

**Comment by huali027** [comment]
@zerodayz, could you please provide one case link with sosreport which includes the output of "ovs_vsctl_list_interface", I searched some cases and sosreports, but all of them don't have the output of "ovs_vsctl_list_interface". I need to know if it is a summary of all interfaces together or separated single interface. Thanks.

**Comment by zerodayz** [comment]
@huali027 As we discussed, the PR https://github.com/sosreport/sos/pull/1698 against sosreport to contain `ovs-vsctl list bridge` in the sosreport archive.

**Comment by huali027** [comment]
@zerodayz, thanks, after the PR is merged, I'll add the new parser.

**Comment by csams** [comment]
@zerodayz @huali027  When the parser is added, please note in its pydoc that it is for sos only.

**Comment by huali027** [comment]
@csams, got it, thanks.
