### ISSUE TITLE
setup_env.sh does not check for the presence of 'virtualenv'

### ISSUE THREAD

**Issue by sterlingalexander** [RedHatInsights/insights-core#1988]
While it does check for some things, the initial install/setup failed for me due to a missing package, virtualenv.  Once I installed it separately everything went smoothly.

A quick but ugly fix would be to add the following to the is_installed() function:

9    pckarr=(git gcc *virtualenv)

**Comment by miclark** [comment]
Created [insights-core-tutorials issue 4](https://github.com/RedHatInsights/insights-core-tutorials/issues/4) for this issue.   Closing this version.
