### ISSUE TITLE
Change sequence of simple_file for first_of Spec for lspci in sos_archive.py

### ISSUE THREAD

**Issue by crackcodecamp** [RedHatInsights/insights-core#1997]
This required to parse contents of lspci file as lspci_-nnvv contains the information of lspci too.

Currently  : 
 `
lspci = first_of([                                                                                             
          simple_file("sos_commands/pci/lspci_-nnvv"),
          simple_file("sos_commands/pci/lspci_-nvv"),
          simple_file("sos_commands/pci/lspci")
      ])
`

After Change
``
lspci = first_of([                                                                                             
          simple_file("sos_commands/pci/lspci_-nnvv"),
          simple_file("sos_commands/pci/lspci"),
          simple_file("sos_commands/pci/lspci_-nvv")
      ])
``

**Comment by xiangce** [comment]
fixed by #1999
