### ISSUE TITLE
NoOptionError using smb.conf parser (samba.py)

### ISSUE THREAD

**Issue by dt8269** [RedHatInsights/insights-core#2018]
Because of this line here:
https://github.com/RedHatInsights/insights-core/blob/f09569e96b861bb10dd5221008077541d3d11776/insights/parsers/samba.py#L75
the smb.conf parser is only reading in the headers. The tests are passing because they're not using the spec. Here's the commit where it was added: 
https://github.com/RedHatInsights/insights-core/commit/9b974af0c9e46cdca0007b3c6fa0ee4275d680cf

**Comment by csams** [comment]
Hey @dt8269 filtering of the spec is intentional since it could contain information we don't want to collect. You'll need to add a filter in your rule, similar to the code you have in the description, to match the lines you need from the file. The patterns aren't regex - just plain strings.

**Comment by dt8269** [comment]
Sorry if I'm misunderstanding but doesn't adding a filter with the string "[" mean that the parser is only provided with lines that contain "["?

The file format is that lines with "[" are headers to sections. The parser is only given the headers but looks for all of the information under each header. For example, in the samba parser docstring it shows an example global section:
```
[global]
  workgroup = MYGROUP
  server string = Samba Server Version %v
  max log size = 50
```
the parser should respond to `samba.getint('global', 'workgroup')` with "WORKGROUP" but instead it raises a NoOptionError because the content it's provided with is only the header text.

**Comment by csams** [comment]
Right, to get the workgroup, you'll need a line somewhere in your code with `add_filter(Specs.samba, ["workgroup"])` to ensure it gets included when filtering is applied. Are you writing rules or working on something else?

**Comment by dt8269** [comment]
Ah okay that will work for my use case. That requirement isn't clear in the samba docs or the insights docs. Maybe there should be a warning, I spent a long time tracking down where the filter was coming from before noticing that line. I still don't fully follow the motivation, is it that smb.conf can be pretty large and we don't want to pull too much into memory? Thanks again for the help.

**Comment by csams** [comment]
@dt8269 Have a look at https://insights-core.readthedocs.io/en/latest/notebooks/Filters%20Tutorial.html. It's generated from one of the interactive notebooks in https://github.com/RedHatInsights/insights-core/tree/master/docs/notebooks. Also have a look at the Insights Core Tutorial notebook and the others, too, for some deep dives. Don't worry much about the Config Tree one for now since that subsystem has been rewritten and is waiting for merge.
