### ISSUE TITLE
ModInfoVeth Parser needs spec for Insights Archives

### ISSUE THREAD

**Issue by bfahr** [RedHatInsights/insights-core#2026]
PR #2000 that added the `ModInfoVeth` parser was missing an insights archive spec.  A new spec needs to be added to `insights/specs/insights_archive` to allow collection of this data from archives.

**Comment by vishwanathjadhav** [comment]
https://github.com/RedHatInsights/insights-core/pull/2027

**Comment by xiangce** [comment]
fixed by #2027
