### ISSUE TITLE
Systemctl cat needs to retain backward compatibility for archive specs

### ISSUE THREAD

**Issue by bfahr** [RedHatInsights/insights-core#2038]
The changes made in PR #1998 to go from a file specs to command specs, result in changes to the location of files in insights archives.  In order to maintain compatibility for archive processing the archive specs should be changed to from `simple_file` to `first_file` and include both the previous file spec and the new file spec.

**Comment by xiangce** [comment]
@chenlizhong - I'm not sure the reason, but this issue is not synced to the new Gitlab repo.

**Comment by chenlizhong** [comment]
@xiangce  This is insights-core, we do not sync it.

**Comment by xiangce** [comment]
Oops 😅

**Comment by bfahr** [comment]
Fixed by #2091
