### ISSUE TITLE
Need a parser for 'rabbitmqctl_report' of containers

### ISSUE THREAD

**Issue by xiangce** [RedHatInsights/insights-core#2049]
The existing `rabbitmq_report` spec and `RabbitmqReport` parser only collect and parse the file get from the host. There are rules need to analyze the same files in the guest containers.

Better add a new parser for the file of containers. And the files are in the same format, but from different paths, the existing `RabbitmqReport` parser can be used as the basic parser.

See: https://github.com/RedHatInsights/insights-core/pull/2045

**Comment by xiangce** [comment]
Due to the `container strategy` does not get a conclusion yet, currently, there is not a good method to collect the files in a container. (`docker exec` is not suggested). We may need to wait for a while to add this parser and spec, until `container strategy` get decided.

**Comment by zerodayz** [comment]
@xiangce Note that from RHEL 8 we have podman and not docker

**Comment by xiangce** [comment]
@zerodayz - May you tell me what's the name of the file in a sos-archive collected in RHEL 8?
