### ISSUE TITLE
Issue in installed_rpms.redhat_signed when run against sosreport

### ISSUE THREAD

**Issue by wushiqinlou** [RedHatInsights/insights-core#2066]
When using insights-run to test sosreport and insights archive from same machine, I got different results for plugin docker_redhat_version. For sosreport, following hit shows in result while no such result in insights archive.

~~~
[FAIL] telemetry.rules.plugins.container.docker_redhat_version.report
---------------------------------------------------------------------
DOCKER_NOT_REDHAT_RELEASE
~~~

The reason is that keyID info checked by installed_rpms.redhat_signed is not collected in sosreport, then the code would return false while docker package is released by RedHat.

**Comment by miclark** [comment]
Note that this only affects certain versions of sosreport.

**Comment by wushiqinlou** [comment]
Fix link: https://github.com/RedHatInsights/insights-core/pull/2093
