### ISSUE TITLE
RFE: add a parser for FreeIPA's HealthCheck logs

### ISSUE THREAD

**Issue by fcami** [RedHatInsights/insights-core#2071]
The [FreeIPA](https://www.freeipa.org/page/Main_Page) project now ships a tool able to detect and in some cases predict future issues with an IPA server: [freeipa-healthcheck](https://github.com/freeipa/freeipa-healthcheck).

The output of this tool is a JSON-formatted array listing all the checks that were done by its plugins.
The tool is also able to log into /var/log/ipa/healthcheck/healthcheck.log every day.

It would be nice if Insights-Core had a parser for such a tool.

**Comment by miclark** [comment]
Addressed by #2072

**Comment by bfahr** [comment]
Fixed by #2072
