### ISSUE TITLE
insights.run does not run against sosreport directory if print_summary=False

### ISSUE THREAD

**Issue by godlike64** [RedHatInsights/insights-core#2107]
I am trying to use insights for a command line tool I'm developing, so as not to duplicate efforts doing many of the things that are already implemented in Insights. For this, I need print_summary to be False, so I can handle the results of each report myself.

However, it appears that when print_summary is set to False, insights does not run against the directory I specified (which is the root of a sosreport), but instead runs against my local system.

Steps to reproduce:

1. Create a script that uses insights-core, such as https://github.com/RedHatInsights/insights-core/blob/master/examples/rules/hostname_rel.py
2. Change the last line (the run() line) to:

~~~
    result = run(report, print_summary=True)
    print(result.get(report))
~~~

3. Run the script against the root of a RHEL sosreport.
4. Change the run() line to set print_summary=False.
5. Run the script again in the same manner.

Actual results:

* On the second run, insight produces the following output:

~~~
Missing Dependencies:
    Requires:
        insights.parsers.hostname.Hostname
    At Least One Of:
        insights.parsers.redhat_release.RedhatRelease
~~~

Output may vary depending on the OS on which the script is run.

Expected results:

* Script should produce the following output:

~~~
RELEASE_IS_RHEL:
    hostname: '<hostname>'
    release : '<version>'
~~~

**Comment by csams** [comment]
Hey @godlike64 , the `print_summary` keyword activates some CLI handling. If you want to call `run` directly yourself and have it work on a sos report, you'll need to pass the path to the report with the `root` keyword: `run(report, root=<path to sos archive or exploded directory>)`.

What kind of command line tool are you developing? We haven't had much interest in integrating at this level from others - just curious what you're working on.
