### ISSUE TITLE
The SELinux combiner doesn't use grub blscfg for RHEL8

### ISSUE THREAD

**Issue by jsvob** [RedHatInsights/insights-core#2138]
* The grub_conf combiner was updated to support blscfg and RHEL8 - https://github.com/RedHatInsights/insights-core/issues/1650

* The SELinux combiner doesn't use the grub_conf combiner, but it uses the grub parsers directly - 
https://github.com/RedHatInsights/insights-core/blob/3.0/insights/combiners/selinux.py#L43. So it doesn't work on RHEL8.

* Expected: The SELinux combiner uses the grub_conf combiner and works on RHEL8.

Thank you.

**Comment by jsvob** [comment]
Hi @xiangce, I've assigned you to this just to give you visibility, since you've worked on https://github.com/RedHatInsights/insights-core/issues/1650. If you delegate it to someone else, that would be none of my business :)

**Comment by xiangce** [comment]
Hi @jsvob, Thanks for that, I will fix it asap.

**Comment by jsvob** [comment]
@xiangce Thank you for the fix!
