### ISSUE TITLE
Request for mpstat parser

### ISSUE THREAD

**Issue by moniCoder** [RedHatInsights/insights-core#2144]
The cpuinfo parser doesn't give utilization and a mdstat parser has been implemented. However mpstat has no parser. Requesting one be written!

**Comment by csams** [comment]
Hey @moniCoder , I don't understand what you mean by "..a mdstat parser has been implemented. However mpstat has no parser." We have an [mdstat parser](https://github.com/RedHatInsights/insights-core/blob/master/insights/parsers/mdstat.py). Can you explain a little more what you need?

**Comment by miclark** [comment]
@csams, I believe the request is to capture the output of the `mpstat` command:
```
-> mpstat
Linux 3.10.0-514.el7.x86_64 (ahost.redhat.com) 	08/19/2019 	_x86_64_	(24 CPU)

09:41:49 AM  CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
09:41:49 AM  all   14.32    0.00    4.32    0.25    0.00    0.06    0.00    0.00    0.00   81.05
```

**Comment by miclark** [comment]
Will the information from `mpstat` be diagnostic?  It seems it grabs a point in time value which may be relevant, but is likely not indicative of the overall state of the system.

**Comment by miclark** [comment]
@moniCoder, any thoughts on the questions, especially from @csams?

**Comment by moniCoder** [comment]
Apologies for the delayed response. The request was for an mpstat parser. The proc/stat parser you have implemented only gave the utilization of the cpu averages (https://github.com/RedHatInsights/insights-core/blob/master/insights/parsers/proc_stat.py) and not the percentages of the individual process categories and their utilization. 

I ended up creating my own mpstat parser from the Parser and spec_factory files to do exactly what I wanted however so you can mark this as closed and solved! 

 Thank you for your responses!
