### ISSUE TITLE
Add support to older sosreport of RHEL6.5 and below

### ISSUE THREAD

**Issue by kenneth-dsouza** [RedHatInsights/insights-core#2196]
On older sosreport version dmesg would be captured under sos_commands/general/dmesg.
Inisght rules would fail in such instances. Add the same in  sos_archive.py file to make it work.
Same goes for blkid, It would be under sos_commands/filesys/blkid.
Let me know if the below changes would be acceptable. I can work on a patch.

Example: For dmesg only.

 # git diff
diff --git a/insights/specs/sos_archive.py b/insights/specs/sos_archive.py
index 3ddb614b..a2acd0fe 100644
--- a/insights/specs/sos_archive.py
+++ b/insights/specs/sos_archive.py
@@ -32,7 +32,7 @@ class SosSpecs(Specs):
     docker_list_containers = first_file(["sos_commands/docker/docker_ps_-a", "sos_commands/docker/docker_ps"])
     docker_list_images = simple_file("sos_commands/docker/docker_images")
     docker_image_inspect = glob_file("sos_commands/docker/docker_inspect_*")
-    dmesg = first_file(["sos_commands/kernel/dmesg", "var/log/dmesg"])
+    dmesg = first_file(["sos_commands/kernel/dmesg", "sos_commands/general/dmesg" "var/log/dmesg"])
     dmidecode = simple_file("sos_commands/hardware/dmidecode")
     dmsetup_info = simple_file("sos_commands/devicemapper/dmsetup_info_-c")
     dumpe2fs_h = glob_file("sos_commands/filesys/dumpe2fs_-h_*")

**Comment by JoySnow** [comment]
Hi @kenneth-dsouza , thanks for raising this issue. 
As we talked, you can go ahead to open a PullRequest for your patch in this repo.

**Comment by JoySnow** [comment]
@kenneth-dsouza  Assign to you, as you are already working on this, to avoid duplicate implementation.

**Comment by xiangce** [comment]
resolved by #2200
