### ISSUE TITLE
Should we convert this multinode parser (metadata.json) to class type ?

### ISSUE THREAD

**Issue by JoySnow** [RedHatInsights/insights-core#221]
This is related to PR: https://github.com/RedHatInsights/insights-core/pull/161

AFAIK:
Fact-1: we like class type parser better than the function type ones.
Fact-2: We'd love to do our best to get the plugins(the @rule reducers) out of troubles.( Let it handle less things.)

Well, based on Fact-1, I am converting this multinode parser from func to class type(suggested by @PaulWay ).
What did I do:
I wrap all the "metadata.json" parsing funcs into one class `MetaData`,
and add (`rhev`, `osp`, `docker`, `metadata`) as `MetaData`'s attributes.
To fit this in insights-plugin side, plugins can be changed like this: 
an example(https://github.com/RedHatInsights/insights-plugins/pull/143)

I test above changes by upload a rhev-coordinator archive to my local insight-engine server, and it works.
(Not guarantee of fully test.)  

When thinking about Fact-2, yes, this change becomes a burden to plugins.
(The existence of metadata.json file means a hit parser for all the @rules which requires it.)

So my question here is: 
Should we convert this multinode parser to class type ?  Or someone has better ideas to achieve this.

**Comment by JoySnow** [comment]
Please do ask me questions if I didn't express myself clearly.

**Comment by JoySnow** [comment]
FYI, https://github.com/RedHatInsights/insights-plugins/issues/144 has a little bit connections with this one.

**Comment by csams** [comment]
Hey @JoySnow, we agree this needs to be addressed and are taking steps in the master branch. We'd still like each environment to have a dedicated component (OSP, RHEV, etc.), and for cluster rules to get the top level component while host level rules get the relevant Child component for a particular host. Have a look at https://github.com/RedHatInsights/insights-core/blob/master/insights/parsers/multinode.py. Note that the metadata decorator is just shorthand for parser(requires=["metadata.json"]) and that we prevent unwanted components from resolving by raising SkipComponent.

**Comment by JoySnow** [comment]
@csams Thanks for your explanation. Great, I can close this issue without changing anything here.

**Comment by JoySnow** [comment]
Close this issue.
