### ISSUE TITLE
Issue with ceph_version parser while parsing the ceph version.

### ISSUE THREAD

**Issue by ashishkumsingh** [RedHatInsights/insights-core#2224]
There is an issue with the regex used in the `ceph_version` parser. Parsing of the ceph version `12.2.8-128` would fail with the current regex.

Also, there is need to update `community_to_release_map` as there are new releases of Ceph.

**Comment by ashishkumsingh** [comment]
@psachin can you review this PR.

**Comment by xiangce** [comment]
Resolved by https://github.com/RedHatInsights/insights-core/pull/2225
