### ISSUE TITLE
Add documentation to  CpuVulns Parser

### ISSUE THREAD

**Issue by bfahr** [RedHatInsights/insights-core#2247]
Please add documentation following the documentation guidelines to the CpuVulns parser that was added in PR #2201.  You can find the documentation guidelines here: https://insights-core.readthedocs.io/en/latest/docs_guidelines.html

**Comment by xhe123** [comment]
Here are the documentation for the parser and combiner, do I need to add more descriptions to improve them?
https://insights-core.readthedocs.io/en/latest/shared_parsers_catalog/cpu_vulns.html
https://insights-core.readthedocs.io/en/latest/shared_combiners_catalog/cpu_vulns_all.html

**Comment by bfahr** [comment]
@xhe123 I did see that it had some documentation, but it is not complete.  If you look at the documentation guidelines the parser should have a brief description, sample inputs and an example section.  These pieces are important for any developer that wants to understand how to use the parser.  One of the big complaints we get is the lack of documentation so it is important to follow the documentation guidelines.

**Comment by xhe123** [comment]
@bfahr I see. Thanks for your answer, I will add description, sample inputs and example section to parser.

**Comment by xiangce** [comment]
@xhe123 - The combiner needs these necessary parts in the docstring as well, please add them to the combiner.

**Comment by xhe123** [comment]
@xiangce ok, I am going to enhance the combiner as well.

**Comment by xhe123** [comment]
Here is the PR for combiner document https://github.com/RedHatInsights/insights-core/pull/2274

**Comment by xiangce** [comment]
Resolved by #2274
