### ISSUE TITLE
Add openvswitch_other_config parser for sosreport

### ISSUE THREAD

**Issue by khomesh24** [RedHatInsights/insights-core#2286]
I find the parser for _openvswitch_other_config_ [1] but I am not able to parse it from the sosreport 
_sos_commands/openvswitch/ovs-vsctl_-t_5_get_Open_vSwitch_._other_config_

[1] https://github.com/RedHatInsights/insights-core/blob/master/insights/parsers/openvswitch_other_config.py

**Comment by khomesh24** [comment]
I suspect we need to add  
`openvswitch_other_config = simple_file("sos_commands/openvswitch/ovs-vsctl_-t_5_get_Open_vSwitch_._other_config")`
in [_insights/specs/sos_archive.py_](https://github.com/RedHatInsights/insights-core/blob/master/insights/specs/sos_archive.py) file.

**Comment by psachin** [comment]
Closing this issue. We will track this issue internally.
