### ISSUE TITLE
SCTPAsc raises exception on RHEL7

### ISSUE THREAD

**Issue by vishwanathjadhav** [RedHatInsights/insights-core#2303]
SCTPAsc raises exception on RHEL-7 because `/proc/net/sctp/assoc` spec contains some extra columns  which are not considere in the current parser.

**Comment by bfahr** [comment]
@vishwanathjadhav can you provide an example or a bit more explanation of the problem here? Thanks.

**Comment by vishwanathjadhav** [comment]
@bfahr - with existing parser there is a fixed set of column_idx which 23 columns on RHEL-6. But on RHEL-7 server same specs contains column_idx which 27 columns. So the exisiting parser throws an exception at

~~~
if "LPORT" not in line or len(line) != keys_cnt:
    raise ParseException("Contents are not compatible to this parser".format(line))
~~~~

**Comment by bfahr** [comment]
@vishwanathjadhav thanks for the explanation.
