### ISSUE TITLE
setup_env.sh not present in fork

### ISSUE THREAD

**Issue by amitkumar50** [RedHatInsights/insights-core#2316]
Following:
https://insights-core-tutorials.readthedocs.io/en/latest/prep_tutorial_env.html

git clone https://github.com/amitkumar50/insights-core
cd insights-core/
ls -ltr 
> cannot find `setup_env.sh`

**Comment by subpop** [comment]
The `setup_env.sh` script is part of the `insights-core-tutorials` repository. https://github.com/RedHatInsights/insights-core-tutorials/blob/master/setup_env.sh

The sample shell commands show cloning the `insights-core-tutorials` repository, followed by `cd insights-core-tutorials`.

> Next you need to run the setup_env.sh script to set up your python environment:
> 
> [userone@hostone work]$ cd insights-core-tutorials
> [userone@hostone insights-core-tutorials]$ setup_env.sh

Give that a try and see if it works.

**Comment by amitkumar50** [comment]
insights-core-tutorials]# ./setup_env.sh 

*** Making sure git and gcc are installed ***
git is installed
gcc is installed

*** Making sure python3.6 is installed ***
Python 3 is not installed
To install, run this command as root: yum install python36

I have python3.7 installed..

**Comment by bfahr** [comment]
Closing this issue since its really related to insights-core-tutorials instead.  Opened issue [10](https://github.com/RedHatInsights/insights-core-tutorials/issues/10) on that project.
