### ISSUE TITLE
Update file paths for foreman related specs as per sosreport changes

### ISSUE THREAD

**Issue by Rohan21Lobo** [RedHatInsights/insights-core#2385]
Since sos-3.7, foreman and related plugins data is collected in native plugins instead of collecing foreman-debug
https://github.com/sosreport/sos/pull/1525

Paths for specs need to be updated

**Comment by Rohan21Lobo** [comment]
> Added new path for ``puppet_ssl_cert_ca_pem`` spec

 Qpid Specs
-------------
For qpid-stat -q

>  In new sos changes, qpid commands were moved to sos's katello plugin. In satellite 6.6, qpid-client cert path got changed from ``/etc/pki/katello/qpid_client_striped.crt`` to ``/etc/pki/pulp/qpid/client.crt`` . This gives 2 combinations : 

* sos_commands/katello/qpid-stat_-u_--ssl-certificate_.etc.pki.pulp.qpid.client.crt_-b_amqps_..localhost_5671
* sos_commands/katello/qpid-stat_-u_--ssl-certificate_.etc.pki.katello.qpid_client_striped.crt_-b_amqps_..localhost_5671

> In sos's code, qpid commands got moved to pulp plugin recently.
https://github.com/sosreport/sos/pull/1805

This gives another 2 combinations : 
* sos_commands/pulp/qpid-stat_-q_--ssl-certificate_.etc.pki.pulp.qpid.client.crt_-b_amqps_..localhost_5671
* sos_commands/pulp/qpid-stat_-q_--ssl-certificate_.etc.pki.katello.qpid_client_striped.crt_-b_amqps_..localhost_5671

This change is yet to be rebased in downstream sos.

Same as above for  qpid-stat -u

**Comment by xiangce** [comment]
#2386 resolved it
