### ISSUE TITLE
The symbolic of simple_file for readlink_e_etc_mtab is incorrect

### ISSUE THREAD

**Issue by xiangce** [RedHatInsights/insights-core#2399]
The symbolic of simple_file for readlink_e_etc_mtab is incorrect

```
readlink_e_etc_mtab = simple_file("readlink_-e_.etc.mtab")
```

the `insights_commands` is missed.

Please use the `mangle` command to generate the symbolic for each `simple_file` spec defined in the `insights_archive.py.

Thanks to @shlao for reporting this issue.

**Comment by xhe123** [comment]
@xiangce  I fixed it in MR https://github.com/RedHatInsights/insights-core/pull/2402 , will you please review? Thanks!
