### ISSUE TITLE
Command spec readlink_e_etc_mtab is missing path for command

### ISSUE THREAD

**Issue by bfahr** [RedHatInsights/insights-core#2409]
The path to the command is missing from the spec `readlink_e_etc_mtab` that was added in PR #2373.  Since the command is run as root when the data is collected, the path needs to be included in the command.

**Comment by xiangce** [comment]
@bfahr  - I believe this issue and #2399 are duplicates. And the #2402 resolved it.

**Comment by xhe123** [comment]
@bfahr I fixed the path missing issue in simple_command() in https://github.com/RedHatInsights/insights-core/pull/2418

**Comment by bfahr** [comment]
Fixed
