### ISSUE TITLE
NeutronConf parser is broken

### ISSUE THREAD

**Issue by mvflusch** [RedHatInsights/insights-core#2412]
I was attempting to use the NeutronConf parser like NovaConf or KeystoneConf and failing.

Comparing the code to NovaConf, if I make the following change it functions correctly.

```
$ git diff parsers/neutron_conf.py

diff --git a/parsers/neutron_conf.py b/parsers/neutron_conf.py
index 3071ac3..4786c76 100644
--- a/parsers/neutron_conf.py
+++ b/parsers/neutron_conf.py
@@ -25,11 +25,9 @@ Sample input data is in the format::
 
 See the ``IniConfigFile`` class for examples.
 """
-from .. import IniConfigFile, parser, add_filter
+from .. import IniConfigFile, parser
 from insights.specs import Specs
 
-add_filter(Specs.neutron_conf, ["["])
-
 
 @parser(Specs.neutron_conf)
 class NeutronConf(IniConfigFile):
```

**Comment by psachin** [comment]
Hi @mvflusch 

I guess you mean to say that `add_filter` which was added in https://github.com/RedHatInsights/insights-core/pull/1400 is causing an issue. It is possible that you are not adding a filter in your rule as below. Can you confirm?

Ex:
```
FILTER="rpc_backend"
add_filter(Specs.neutron_conf, FILTER)
```

May I know how are you using this parser?

**Comment by psachin** [comment]
Closing this issue as there was no response from the reporter. Feel free to re-open this issue if required.
