### ISSUE TITLE
Issue with 'firewalld_conf' spec collection

### ISSUE THREAD

**Issue by rasrivas-redhat** [RedHatInsights/insights-core#2485]
There is an issue with 'firewalld_conf' spec collection as currently `firewalld_conf = RegistryPoint(filterable=True)` is configured, which should be `firewalld_conf = RegistryPoint()` inspec init file

Core PR: https://github.com/RedHatInsights/insights-core/pull/2484

**Comment by xiangce** [comment]
@rasrivas-redhat , Since this file may contain sensitive information, so it's filtered. You may want to add the required `keywords` by using the add_filters() in the rule.

**Comment by rasrivas-redhat** [comment]
@xiangce - ack, we can close this issue and Core PR: https://github.com/RedHatInsights/insights-core/pull/2484
