### ISSUE TITLE
RhsmReleaseVer does not handle when release version is None

### ISSUE THREAD

**Issue by vishwanathjadhav** [RedHatInsights/insights-core#2509]
RhsmReleaseVer does not handle when the release version is None. 
Sample input data is as below(RHEL7): 
~~~
'{"releaseVer": null}' 
~~~

**Comment by amitkumar50** [comment]
Will adding check for `null` in parse_content help?

    if rel is 'null':
       return

**Comment by vishwanathjadhav** [comment]
@amitkumar50  - we can not return empty as it is one of the expected settings.
The implementation in the [PR](https://github.com/RedHatInsights/insights-core/pull/2510/files) makes sure that the value is **_null_** and it should be kept **_empty_**.
