### ISSUE TITLE
Fix collection of lvm configuration information

### ISSUE THREAD

**Issue by kergon** [RedHatInsights/insights-core#2554]
While most systems just use a single lvm configuration file, lvm.conf, the system allows the content to be split across multiple files.  Most of the lvm.conf data collected by Insights at the moment seems to be comment lines!

Instead of attempting to replicate how lvm deals with configuration, inevitably handling some cases incorrectly, Insights should use the "lvmconfig" command (with appropriate arguments e.g. "--type full") to obtain the actual configuration information that lvm is using.  This is available since 2015, version 2.02.123 or as 'lvm dumpconfig' (with fewer options) in older versions.

**Comment by kergon** [comment]
Individual settings can be obtained by:  

# lvmconfig global/locking_type
locking_type=1

The development team could enable --reportformat json for that command too, making it easy to pass the whole pre-processed configuration through for rules to use.

**Comment by csams** [comment]
Awesome info! Thanks for opening the issue! We'll need to figure out how to ingest the data both ways so we can still support sosreports, but we definitely prefer the system to give us a completely processed configuration tree instead of trying to back our way into it. And if we can get it in json so we don't need to figure out an app specific grammar, that's even better.

It seems like this would also be a good enhancement to sos.

**Comment by kergon** [comment]
sosreports calls out to lvmdump to gather its information (which gathers a lot more diagnostics).  We could wrap the output for insights with that too, and then sosreport could automatically include identical output to what Insights get.  (This would only be for future releases, not when run on systems not upgraded to the release where the change happened.)

**Comment by kergon** [comment]
Here's a test case that separates the old and new code (for the lvmconfig parsing):

On a default install, add the following line to the bottom of /etc/lvm/lvm.conf:
tags { tag1{} }

Create the file /etc/lvm/lvm_tag1.conf as follows:
activation {
thin_pool_autoextend_percent = 25
}

This changes the threshold for thin pool autoextension from 20% to 25%. (It defines a host tag that instructs lvm to read in an additional config file with a setting thats override the original.)

The current version of insights-client incorrectly reports 20. The new version should report 25.

**Comment by kergon** [comment]
The 'WARNING' line goes to stderr (and shouldn't happen if the insights-client is running as root).  There might be other lines too, so can you just capture stdout without stderr?
