### ISSUE TITLE
Reporting the wrong number of cores_total

### ISSUE THREAD

**Issue by iphands** [RedHatInsights/insights-core#2555]
Hi folks...

I think we are noticing a bug that comes from a misunderstanding of cpuinfos processor[N]."cpu_cores" value.

That value is not a count of cores per "cpu". Instead it is a count of the cores on the logical cpus parent package.

i.e. for 2x 6 core CPUs each cpu stanza (12 of them) should show "cpu cores : 6"
But there are not 12x6 cpus. There are 12.

In a big.little arch with 1x 4 core and 1x 2 core you'd see
processor       : 0
cpu cores       : 4
...
processor       : 1
cpu cores       : 4
...
processor       : 2
cpu cores       : 4
...
processor       : 3
cpu cores       : 4
...
processor       : 4
cpu cores       : 2
...
processor       : 5
cpu cores       : 2

**Comment by iphands** [comment]
For example on my 32 core system:
```
[root@noir ~] cat /proc/cpuinfo  | fgrep processor | wc -l
32
[root@noir ~] cat /proc/cpuinfo  | fgrep cores
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
cpu cores	: 8
```

Insights would tell me I have 8 x 32 cores. Which is not true.
I have 2 E5-2670's. https://ark.intel.com/content/www/us/en/ark/products/64595/intel-xeon-processor-e5-2670-20m-cache-2-60-ghz-8-00-gt-s-intel-qpi.html
Each has 16 cores per linux threading hypertheading cores as cores, for a total of 32. (8x2x2)

**Comment by iphands** [comment]
Here are some deets:
https://github.com/torvalds/linux/blob/master/arch/x86/kernel/smpboot.c#L569

**Comment by iphands** [comment]
I would also argue that we should consider only ever emitting "cores_per_socket" on arches that we know are heterogeneous or we look at all instances of "cpu cores" and see they are the same.

https://github.com/torvalds/linux/blob/master/arch/x86/kernel/smpboot.c#L1407

**Comment by iphands** [comment]
So if each instance of "cpu cores" == the value of "cpu cores"[0] then emit "cores_per_socket" else we should not emit.

**Comment by bfahr** [comment]
@iphands I agree the filed `core_total` is wrong and something needs to be done with the attribute.  I think it may make more sense to remove this attribute and recommend use of the [lscpu parser](https://github.com/RedHatInsights/insights-core/blob/master/insights/parsers/lscpu.py) instead since that command summarizes the information from `/proc/cpuinfo` and should provide a more accurate answer.

**Comment by shlao** [comment]
> For example on my 32 core system:
> 
It's 2 sockets (2 physical cpu)( 8 cores per cpu), so you only have 16 cores.

**Comment by iphands** [comment]
> @iphands
> 
> > For example on my 32 core system:
> 
> It's 2 sockets (2 physical cpu)( 8 cores per physical cpu), so you only have 16 cores.

```
[root@noir ~] cat /proc/cpuinfo | fgrep processor | wc -l
32

[root@noir ~] lscpu | fgrep On-line
On-line CPU(s) list:             0-31
```

No I have 2 packages 8 full execution units per package and 8 hyper threading units per package.
(8+8) * 2... 32

The only caveat with this CPU is Linux (including cpuinfo, lscpu data)  treats hyper-threading units as full cpus. That is only tangentially related to this bug though.

The parser is wrong man... read the kernel code.

**Comment by shlao** [comment]
As what the document says in https://ark.intel.com/content/www/us/en/ark/products/64595/intel-xeon-processor-e5-2670-20m-cache-2-60-ghz-8-00-gt-s-intel-qpi.html
```
# of Cores 8
# of Threads 16
```

You only have  8 cores per CPU, and you have 2 CPUs (2 sockets), so you 8 * 2 = 16 cores
 If HT is enabled, then You can see 16 Logic CPU in command per CPU `cat /proc/cpuinfo | fgrep processor`

I think we can't mix the CPU core and Logic CPU.

Yes, it's true that is wrong in code:
```
241     def core_total(self):
245         if self.data and 'cpu_cores' in self.data:
246             return sum([int(c) for c in self.data['cpu_cores']])
```

It should be:
```
241     def core_total(self):
245         if self.data and 'cpu_cores' in self.data:
246             return int(self.data['cpu_cores'] * self.data['sockets'])
```

The means of cpu_cores is `/proc/cpuinfo` is how many physical 
A core is the smallest independent unit that implements a general-purpose processor; 
Hyperthreading isn't an independent unit as a general-purpose processor.

Ref https://doc.callmematthi.eu/static/webArticles/Understanding%20Linux%20_proc_cpuinfo.pdf

**Comment by shlao** [comment]
What we can read from https://www.kernel.org/doc/Documentation/x86/topology.txt
```
  Thread-related topology information in the kernel:
  - topology_sibling_cpumask():

    The cpumask contains **### all online threads** in the core to which a thread belongs.
```
so, https://github.com/torvalds/linux/blob/master/arch/x86/kernel/smpboot.c#L609-L620
```
603     for_each_cpu(i, cpu_sibling_setup_mask) {
612		if (cpumask_weight(topology_sibling_cpumask(cpu)) == 1) {
615                  * for each core in package, increment
618			if (cpumask_first(topology_sibling_cpumask(i)) == i)
620				c->booted_cores++;
```

So, ``` cpumask_first(topology_sibling_cpumask(i)) == i    ``` it means that if it is the first the online thread of the CPU core then  it increments the booted_cores.

So Logic CPU and CPU core are different 

So Hyperthread is regarded as a logic cpu in linux kernel, not a physical cores.

**Comment by iphands** [comment]
Sorry yeah I think that is proper.
This is not though I think:

> It should be:
> 
> 241     def core_total(self):
> 245         if self.data and 'cpu_cores' in self.data:
> 246             return int(self.data['cpu_cores']) * int(self.data['sockets'])

I'm not a Python guy, but believe that int(list) * int(list) is incorrect, right?
I think this is more appropriate:
```python
    @property
    @defaults()
    def core_total(self):
        """
        str: Returns the total number of cores for the server if available, else None.
        """
        if self.data and 'cpu_cores' in self.data:
            return int(len(sorted(set(self.data['sockets'])))) * int(self.data['cpu_cores'][0])
        else:
            return None
```

Its the number of sockets total * the number of cpu_cores found on each socket.. which is uniform on x86.

Not the length of the set of sockets found in cpuinfo * the length of the 'cpu cores' values found in cpuinfo.

That last `int(self.data['cpu_cores'][0])` assumes a lot about the arch though.
