### ISSUE TITLE
Parser for /proc/sys/net/ipv4/tcp_rmem & /proc/sys/net/ipv4/tcp_wmem

### ISSUE THREAD

**Issue by yadneshk** [RedHatInsights/insights-core#2557]
The files `/proc/sys/net/ipv4/tcp_rmem` & `/proc/sys/net/ipv4/tcp_wmem` contain the minimum, default and maximum socket buffer values which can be used by a specific socket connection.

**Comment by psachin** [comment]
@yadneshk Please go ahead and raise the PR.

**Comment by bfahr** [comment]
@psachin @yadneshk its not clear that this is an issue.  What is the associated problem that needs to be addressed?
