### ISSUE TITLE
YumReposD parser considers all files in yum.repos.d instead .repo files

### ISSUE THREAD

**Issue by Rohan21Lobo** [RedHatInsights/insights-core#2689]
Currently the Spec collects all files in yum.repos.d
```
$ egrep yum_repos_d default.py
    yum_repos_d = glob_file("/etc/yum.repos.d/*")
```
Customers often keep files like something.repo.old or .bak and parser considers them and rules using this gives false results.

Only *.repo files need to be considered by spec/parser as yum/dnf ignores all other files.

**Comment by bfahr** [comment]
PR #2690 has been merged.
