### ISSUE TITLE
Insights client run leaves temp directories under /tmp/

### ISSUE THREAD

**Issue by Rohan21Lobo** [RedHatInsights/insights-core#2721]
It seems that temporary directories leftovered in /tmp, Two situations as per my observation: 
* When new egg is downloaded and updated,  a temp directory is leftovered with the download egg and gpg signature
* when egg is not updated, it just leaves a empty temp directory in /tmp

**Comment by Rohan21Lobo** [comment]
MR : https://github.com/RedHatInsights/insights-core/pull/2722

**Comment by bfahr** [comment]
@Rohan21Lobo is this fixed by #2722 ?

**Comment by Rohan21Lobo** [comment]
> @Rohan21Lobo is this fixed by #2722 ?

Yes this was fixed in that ME. Closing issue.
