### ISSUE TITLE
Specs are generated with different sort

### ISSUE THREAD

**Issue by vishwanathjadhav** [RedHatInsights/insights-core#2746]
Specs added in `insights/specs/insights_archive.py` are in unexpected order as that of generating in the insights archive.
As per the insights_archive.py the specs are supposed to be `insights_commands/ls_-lan_.etc_.etc.cloud.cloud.cfg.d_.etc.nova.migration_.etc.pki.ovirt-vmconsole_.etc.pki.tls.certs_.etc.pki.tls.private_.etc.rc.d.init.d_.etc.sysconfig` but in insights_archive specs are generated in `insights_commands/ls_-lan_.etc_.etc.cloud.cloud.cfg.d_.etc.nova.migration_.etc.pki.ovirt-vmconsole_.etc.pki.tls.certs_.etc.pki.tls.private_.etc.sysconfig_.etc.rc.d.init.d` Hence updating the specs

**Comment by vishwanathjadhav** [comment]
@bfahr , @xiangce - Please review the issue.

**Comment by xiangce** [comment]
@vishwanathjadhav - This is not an issue of `insights-core` but an issue of the `uploader.json`. Please fix it in the `insights-core-assets` repo.

**Comment by vishwanathjadhav** [comment]
The issue is fixed in uploader.json
