### ISSUE TITLE
Multiple "sos_commands" directories result in incorrect "root"

### ISSUE THREAD

**Issue by xiangce** [RedHatInsights/insights-core#2772]
There are some sosreport archives include multiple "sos_commands" directories in different level, e.g.

```
# tree sosreport-test | egrep "npm|sos_commands|sos_strings"
...
├── route -> sos_commands/networking/route_-n
├── sos_commands
│   ├── npm
│   │   ├── npm_config_list_global
│   │   └── npm_ls_global
├── sos_strings
│   ├── npm
│   │   └── sos_commands
│   │       └── npm
...

# ls -l sosreport-test/sos_strings/npm
total 0
drwx------@ 3 liuxc  wheel  96 Jun  1 20:46 sos_commands
# ls -d sosreport-test/sos_commands
sos_commands

```

This results in the framework get the dir `"sosreport-test/sos_strings/npm"`as the `"root"` of this archive incorrectly instead of the "sosreport-test/" (It iterates the `"sos_strings"` before the `"sos_commands"`) and then results in `non-hit` on some `must-hit` hosts.

https://github.com/RedHatInsights/insights-core/blob/a29ed0df7b387bc26462d76acec87ac7c1820012/insights/core/context.py#L165-L170

@huali027 is trying to resolve it via #2765 by setting the candidate which is closest to the real root as the `root`, but I think it's a common issue and may relate to the policy of insights about how to explore the structure of target archives. @jhjaggars, @csams, @bfahr - Would you mind taking a look?

**Comment by bfahr** [comment]
@xiangce have you tested this again now that #2765 has been merged?

**Comment by huali027** [comment]
@xiangce @bfahr, I tested the sosreport with two "sos_commands", and it works well with the latest insights-core.

**Comment by xiangce** [comment]
@huali027 - Thanks for the confirmation. I also confirmed that with this patch, the insights-core could find the `sos_commands` dir correctly.

```
❯ find /tmp/sosreport-appl111-lon-2020-06-01-hhbalac | grep  "sos_commands\$"
/tmp/sosreport-appl111-lon-2020-06-01-hhbalac/sos_strings/npm/sos_commands
/tmp/sosreport-appl111-lon-2020-06-01-hhbalac/sos_commands
```

* With the patch, there are rules getting fired.
```
❯ git --no-pager log | head
commit d110ceaa8092816b4701093c5f55695108ec4159
Author: Glutexo <stomsa@redhat.com>
Date:   Tue Oct 27 14:00:00 2020 +0100

❯ insights-run -p telemetry/rules/plugins/kernel /tmp/sosreport-appl111-lon-2020-06-01-hhbalac
---------
Progress:
---------
EESSSSM.SSFFSS.SSFSSSSSSSSSSSSSSSSSS

...

----------------------
Rule Execution Summary
----------------------
Passed      : 0
Failed      : 3
Info        : 0
Missing Deps: 28
Fingerprint : 0
Metadata    : 1
Metadata Key: 0
Exceptions  : 2

```

* Without the patch, no rules get fired.
```
❯ git --no-pager log | head
commit a29ed0df7b387bc26462d76acec87ac7c1820012
Author: Xiangce Liu <xiangceliu@redhat.com>
Date:   Thu Sep 24 03:44:12 2020 +0800

❯ insights-run -p telemetry.rules.plugins.kernel /tmp/sosreport-appl111-lon-2020-06-01-hhbalac
---------
Progress:
---------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

--------------
Rules Executed
--------------

----------------------
Rule Execution Summary
----------------------
Passed      : 0
Failed      : 0
Info        : 0
Missing Deps: 115
Fingerprint : 0
Metadata    : 0
Metadata Key: 0
Exceptions  : 0
```

**Comment by xiangce** [comment]
@bfahr - I will close this issue.
