### ISSUE TITLE
The "du_dirs" spec cannot be collected via the new core collection

### ISSUE THREAD

**Issue by xiangce** [RedHatInsights/insights-core#2824]
The current implementation
```python
du_dirs = foreach_execute(['/var/lib/candlepin/activemq-artemis'], "/bin/du -s -k %s")
```
It cannot be collected and reports:
```
# insights cat du_dirsMissing Dependencies:
    At Least One Of: 
        insights.specs.default.DefaultSpecs.du_dirs
        insights.specs.insights_archive.InsightsArchiveSpecs.du_dirs
```

After modify it as:
```python
@datasource()
def dus(broker):
    return ['/var/lib/candlepin/activemq-artemis']
du_dirs = foreach_execute(dus, "/bin/du -s -k %s")
```
It can be collected:
```
# insights cat du_dirs
CommandOutputProvider("'/bin/du -s -k /var/lib/candlepin/activemq-artemis'")
984	/var/lib/candlepin/activemq-artemis
```

It seems that we can only define the dependencies as `@datasource` to make it works.
Is this designed on purpose? If so, we should update the definition of the `du_dirs` as above.

**Comment by bfahr** [comment]
@xiangce `foreach_execute` requires a datasource or a list of datasources as the first argument.  The list of strings is working, but when core tries to find the datasource it is not present and the spec is marked as having missing dependencies.  Your proposed solution, adding the `dus` datasource, is the correct way to fix this spec.

**Comment by xiangce** [comment]
@bfahr - Thanks for helping me fix it.
