### ISSUE TITLE
insights-run throw UnicodeEncodeError: 'utf-8' codec can't encode characters in position X-X: surrogates not allowed

### ISSUE THREAD

**Issue by akshay196** [RedHatInsights/insights-core#2832]
When running "insights-run" with -t (print traceback) enabled, it exited throwing "UnicodeEncodeError" error. See below:

```bash
---------
Progress:
---------
PE
Tracebacks:
Traceback (most recent call last):
  File "/home/akgaikwad/projects/insights/py3.6env/bin/insights-run", line 33, in <module>
    sys.exit(load_entry_point('insights-core', 'console_scripts', 'insights-run')())
  File "/home/akgaikwad/projects/insights/insights-core/insights/__init__.py", line 420, in main
    run(print_summary=True)
  File "/home/akgaikwad/projects/insights/insights-core/insights/__init__.py", line 368, in run
    formatter.postprocess(broker)
  File "/home/akgaikwad/projects/insights/insights-core/insights/formats/text.py", line 221, in postprocess
    self.formatter.postprocess()
  File "/home/akgaikwad/projects/insights/insights-core/insights/formats/text.py", line 185, in postprocess
    self.show_tracebacks()
  File "/home/akgaikwad/projects/insights/insights-core/insights/formats/text.py", line 137, in show_tracebacks
    print(t, file=self.stream)
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 2330-2331: surrogates not allowed
```
Text formatter does not handle [surrogate](https://en.wikipedia.org/wiki/Universal_Character_Set_characters#Surrogates) while printing traceback.

**How to reproduce:**
1. Copy the below content in the file "date" 
```
2020Äê 11ÔÂ 23ÈÕ ÐÇÆÚÒ» 15:37:43 CST
```
2. Execute below command:
```bash
insights-run -p insights.parsers.date,insights.plugins.always_fires -b date=date -t
```
This throw an "UnicodeEncodeError" error.

**Expected output:**
```
---------
Progress:
---------
P

--------------
Rules Executed
--------------
[PASS] insights.plugins.always_fires.report
-------------------------------------------

ALWAYS_FIRES:
    kernel: 'this is junk'

----------------------
Rule Execution Summary
----------------------
Passed      : 1
Failed      : 0
Info        : 0
Missing Deps: 0
Fingerprint : 0
Metadata    : 0
Metadata Key: 0
Exceptions  : 0
```

**Comment by koalakangaroo** [comment]
@xiangce @chenlizhong - take a look pls

**Comment by xiangce** [comment]
@akshay196 - I didn't reproduce the `UnicodeEncodeError` on my side but get a `ValueError` like below instead

```
ValueError: time data '2020Äê 11ÔÂ 23ÈÕ ÐÇÆÚÒ» CST' does not match format '%a %b %d %H:%M:%S %Y'
```

And I think this is expected unless the `2020Äê 11ÔÂ 23ÈÕ ÐÇÆÚÒ» CST` is a correct format. But I don't think it is.

For this incorrect format, what kind of `Exception`s do you think is appropriate?

**Comment by akshay196** [comment]
@xiangce Little change in reproduce step above. Instead of copying text, download date file from [here](https://share.riseup.net/#zaRK98cRkfNIPauiSdOCng) This file is gathered in one of the sosreport I have.

I have seen `UnicodeEncodeError` multiple times mainly due to such date file. If anyhow we can handle `UnicodeEncodeError` to occur that would be better instead of exiting insights-run command without any rule report.
