### ISSUE TITLE
run parsers and combiners (and rules) during collection

### ISSUE THREAD

**Issue by gavin-romig-koch** [RedHatInsights/insights-core#290]
(This is part of a list of the major stuff that needs to be done as part of a 'Custom Rules' MVP; before we can say Custom Rules work, though I think we want to do this one even if we don't do Custom Rules.) 

In the collector (client), run the parsers and combiners, and upload their results instead of the raw specs results.

1. the parsers and combiners become a published API that we can no longer change at will.  Customers will be writing rules depending on the existing parsers and combiners.
2. the result of any individual parser or combiner might be needed by Custom Rules, Server Rules, both Custom and Server, or neither.  If the results of a parser or combiner is not needed by the Server, it should not be uploaded (for security and space reasons).  If neither, they can just not be run.

**Comment by csams** [comment]
This is possible with core 3.x and the new client delivery method, although the version of custom rules described here may no longer be applicable.
