### ISSUE TITLE
"runnable rules"

### ISSUE THREAD

**Issue by gavin-romig-koch** [RedHatInsights/insights-core#292]
(This is part of a list of the major stuff that needs to be done as part of a 'Custom Rules' MVP; before we can say Custom Rules work.)

For people to be able to generate Custom Rules, they are going to need to be able to run them.  They will not have a large body of sosreports available to them, nor the accumulated data from lots of Insights archives.

They can test their rules by building py.tests as we do, but that assumes they know python and py.test, and forces them to learn how to use our integration tests framework.

They can set up some test boxes and install their fledgling Custom rules, and look at the result in Insights.  But what if nothing shows up, what do they do then.

At minimum we need a way to run a rule against the data on this box.  See results, see errors, see debugging information.

It would be nice to be able to run against another box, sorta like ansible.  See results, see errors, see debugging information.

It would be nice if you could run something like our integration tests without having to know python or py.test or our integration testing framework.

**Comment by PaulWay** [comment]
@gavin-romig-koch this is exactly what I've been pushing for - letting people test rules by running a simple command on their own machine.

The simple workaround at the moment is for them to use 'sosreport' to get a snapshot of the machine, and then run the insights-cli on that.  That does save the tester re-running all the commands, so IMO any eventual client we produce should be able to save, and work off, a 'machine snapshot' or whatever cool name we can come up with, because sosreport is not a cool name :-)  That would also provide a kind of 'run against another box' functionality.

I believe @csams is working on a modern client - we should talk to him.

**Comment by csams** [comment]
@gavin-romig-koch @PaulWay Here's a script using 2.x that runs a standard spec, standard parser, and custom rule on the current machine. Just ensure insights-core is on the python path:

```python
#!/usr/bin/env python
from insights.core.plugins import make_response, rule
from insights.parsers.redhat_release import RedhatRelease

@rule(RedhatRelease)
def report(rel):
    """Fires if you're running Fedora."""

    if "Fedora" in rel.product:
        return make_response("IS_FEDORA")

if __name__ == "__main__":
    from insights import run
    run(report, print_summary=True)
```
Here's one that's a little more complicated that includes a custom spec, parser, and rule:
```python
#!/usr/bin/env python
from __future__ import print_function
from collections import namedtuple

from insights import get_active_lines, parser, Parser
from insights import make_response, rule, run
from insights.core.spec_factory import SpecFactory

sf = SpecFactory("insights.specs")
hosts = sf.simple_file("/etc/hosts", name="hosts")

@parser(hosts)
class HostParser(Parser):
    Host = namedtuple("Host", ["ip", "host", "aliases"])

    def parse_content(self, content):
        self.hosts = []
        for line in get_active_lines(content):
            # remove inline comments
            line = line.partition("#")[0].strip()

            # break the line into parts
            parts = line.split()
            ip, host = parts[:2]
            aliases = parts[2:]

            self.hosts.append(HostParser.Host(ip, host, aliases))

    def __repr__(self):
        me = self.__class__.__name__
        msg = "%s([" + ", ".join([str(d) for d in self.hosts]) + "])"
        return msg % me

@rule(HostParser)
def report(hp):
    if len(hp.hosts) > 1:
        return make_response("ERROR_KEY_TOO_MANY_HOSTS", number=len(hp.hosts))

if __name__ == "__main__":
    run(report, print_summary=True)
```
If we get insights-core into pypi (and/or an easy to install rpm), this kind of thing would be available to whoever wants to use it. It should be straightforward to send a script like this to a remote box, run it, and collect the output.

The `run` function also returns the object holding all component results (basically a fancy version of `shared`), so it's easy to disable the standard text summary and print whatever custom output makes sense.

**Comment by csams** [comment]
Runnable rules are available in 3.x
