### ISSUE TITLE
The insights archive spec in #3061 also needs to be updated for the change to pmrep_metrics spec

### ISSUE THREAD

**Issue by bfahr** [RedHatInsights/insights-core#3065]
@wushiqinlou in your PR #3061 that was merged you also need to update the [insights archive spec](https://github.com/RedHjatInsights/insights-core/blob/57ab772ea8eb9f3061d6a356ea78bcef07ecdc4f/insights/specs/insights_archive.py#L190) to either a glob spec, or a first_file spec to collect all of the data.

**Comment by wushiqinlou** [comment]
Fixed MR: https://github.com/RedHatInsights/insights-core/pull/3068

**Comment by xiangce** [comment]
@bfahr - Thanks for the double check. and Sorry for missing this point.
