### ISSUE TITLE
NeutronConf doesn't parse all parameters of the config file

### ISSUE THREAD

**Issue by yadneshk** [RedHatInsights/insights-core#3134]
OpenStack 16.1 sample Neutron config file
```
$ egrep -ivh "^$|^#" ~/sosreport-overcloud-controller/var/lib/config-data/puppet-generated/neutron/etc/neutron/neutron.conf | grep keystone_auth -A5
[keystone_authtoken]
www_authenticate_uri=http://172.22.214.131:5000
region_name=regionOne
memcached_servers=172.22.214.149:11211,172.22.214.191:11211,172.22.214.202:11211
memcache_use_advanced_pool=True              <<<<<<<<<<<<<<<<<<<<<
auth_type=password
```

While fetching value for param `memcache_use_advanced_pool` from Neutron config, the section name 
`keystone_authtoken` was found however the param was not found.
```
(Pdb) neutron_conf.sections
<bound method IniConfigFile.sections of INI file 'neutron.conf' - sections:odict_keys(['cors', 'database', 
'keystone_authtoken', 'oslo_concurrency', 'oslo_messaging_amqp', 'oslo_messaging_kafka', 
'oslo_messaging_notifications', 'oslo_messaging_rabbit', 'oslo_middleware', 'oslo_policy', 'privsep', 
'ssl', 'agent', 'nova', 'placement', 'ovs', 'quotas'])> 
 
(Pdb) neutron_conf.has_option('keystone_authtoken','memcache_use_advanced_pool')
False
 
(Pdb) neutron_conf.get('keystone_authtoken','memcache_use_advanced_pool')
*** insights.contrib.ConfigParser.NoOptionError: No option 'memcache_use_advanced_pool' in section: 'keystone_authtoken'
(Pdb)
```

Upon eliminating the [filters](https://github.com/RedHatInsights/insights-core/blob/master/insights/parsers/neutron_conf.py#L31-L43) from NeutronConf parser, all params got parsed successfully.

Structure of neutron config file is very much similar to other openstack service configs.

Parsers for [NovaConf](https://github.com/RedHatInsights/insights-core/blob/master/insights/parsers/nova_conf.py) and [CinderConf](https://github.com/RedHatInsights/insights-core/blob/master/insights/parsers/cinder_conf.py) do not have such filters added.

**Comment by psachin** [comment]
/ We are confirming this issue internally /

**Comment by psachin** [comment]
Adding a filter within a rule should solve this issue,

```
add_filter(Specs.neutron_conf, "memcache_use_advanced_pool")

```
