### ISSUE TITLE
Update yaml.load to yaml.safe_load

### ISSUE THREAD

**Issue by csams** [RedHatInsights/insights-core#316]
"[Warning: It is not safe to call yaml.load with any data received from an untrusted source! yaml.load is as powerful as pickle.load and so may call any Python function](http://pyyaml.org/wiki/PyYAMLDocumentation#LoadingYAML)."

We should update uses of yaml.load to yaml.safe_load where possible.

**Comment by jhjaggars** [comment]
Is there any reason we can't just switch?

**Comment by csams** [comment]
I don't see any reason. `yaml.load` is dangerous because it can dump and load arbitrary objects, and our current uses of the module don't need to do that.

```python
yaml.load("""
!!python/object:__main__.Hero
name: Welthyr Syxgon
hp: 1200
sp: 0
""")
```

**Comment by csams** [comment]
Changes merged in master.
