### ISSUE TITLE
Spec systemctl_cat_dnsmasq_service needs an insights archive spec

### ISSUE THREAD

**Issue by bfahr** [RedHatInsights/insights-core#3165]
The new spec `systemctl_cat_dnsmasq_service` added in PR #3155 is missing a corresponding spec in `insights/specs/insights_archive.py`.

**Comment by rasrivas-redhat** [comment]
@bfahr - Thanks for catching the issue, have raised an MR: https://github.com/RedHatInsights/insights-core/pull/3166 to fix this issue, please check when you get some time.
