### ISSUE TITLE
The combiner "SatelliteVersion" isn't accurate when the package "satellite" and "satellite-capsule" are installed at the same time

### ISSUE THREAD

**Issue by huali027** [RedHatInsights/insights-core#3335]
From some archives, I found sometimes the packages "satellite" and "satellite-capsule" are installed at the same time. In this way, the combiner "SatelliteVersion" will consider it is a satellite server. However, from /etc/rhsm/rhsm.conf we can see it's not the  CDN URL, so it should be a satellite capsule. We need to enhance it.

**Comment by xiangce** [comment]
Resolved by #3336
