### ISSUE TITLE
When filters are added for a spec which is collected by glob_file, the parser can not get the files when one of the files does not contain the filtered lines

### ISSUE THREAD

**Issue by huali027** [RedHatInsights/insights-core#3356]
An example is:
rsyslog_conf = RegistryPoint(filterable=True, multi_output=True)
rsyslog_conf = glob_file(["/etc/rsyslog.conf", "/etc/rsyslog.d/*.conf"])
When I tested it, I found the file "/etc/rsyslog.conf" contains the filtered lines, but the file "/etc/rsyslog.d/listen.conf" doesn't contain the filtered lines.
In the created archive, it is like:
`{"exec_time": 6.890296936035156e-05, "ser_time": 0.05234384536743164, "errors": ["Traceback (most recent call last):\n  File \"/var/lib/insights/newest.egg/insights/core/serde.py\", line 195, in dehydrate\n    doc[\"results\"] = marshal(value, root=self.data, pool=self.pool)\n  File \"/var/lib/insights/newest.egg/insights/core/serde.py\", line 105, in marshal\n    return [f(t) for t in v]\n  File \"/var/lib/insights/newest.egg/insights/core/serde.py\", line 85, in serialize\n    \"object\": to_dict(obj, root=root),\n  File \"/var/lib/insights/newest.egg/insights/core/spec_factory.py\", line 1041, in serialize_text_file_provider\n    rc = obj.write(dst)\n  File \"/var/lib/insights/newest.egg/insights/core/spec_factory.py\", line 288, in write\n    p.write(dst)\n  File \"/var/lib/insights/newest.egg/insights/util/subproc.py\", line 155, in write\n    six.reraise(be.__class__, be, sys.exc_info()[2])\n  File \"/var/lib/insights/newest.egg/insights/util/subproc.py\", line 151, in write\n    raise CalledProcessError(rc, self.cmds[0], \"\")\nCalledProcessError: (1, ['grep', '-F', '$ActionQueueFileName\\n)\\n(\\n{\\n}\\nimjournal', '/etc/rsyslog.d/listen.conf'], '')\n"], "name": "insights.specs.Specs.rsyslog_conf", "results": null}`
As a result, the parser can't continue since it doesn't get the collected files.
However, the expected result is the parser can get the "/etc/rsyslog.conf" file since it contains what we wanted.

**Comment by xiangce** [comment]
Thanks for reporting this issue, I do think this is a bug of the core_collection, it should skip the files which can be collected of the `glob_file` when there are some unable to collect.

https://github.com/RedHatInsights/insights-core/blob/687dbe59155a2b187b00c6690df8f71d939e2499/insights/core/serde.py#L193-L200

The exception should be handled within the `marshal` function, but not after it.

https://github.com/RedHatInsights/insights-core/blob/687dbe59155a2b187b00c6690df8f71d939e2499/insights/core/serde.py#L97-L106

Do you want to give it a try or just leave it me?

**Comment by huali027** [comment]
@xiangce  thanks for the quick findings, let me try first, if I face any problems, I'll ask you for help.
