### ISSUE TITLE
Missing dependencies when inspect parsers using Python 3.10

### ISSUE THREAD

**Issue by shzhou12** [RedHatInsights/insights-core#3405]
~~~
# cat /root/insights-vagrant-host-20180406174409/etc/redhat-release 
Red Hat Enterprise Linux Server release 7.4 (Maipo)

# insights inspect insights.parsers.redhat_release.RedhatRelease /root/insights-vagrant-host-20180406174409/ -D
DEBUG:insights.core.dr:Importing insights.specs.default
DEBUG:insights.core.dr:Importing insights.specs.insights_archive
DEBUG:insights.core.dr:Importing insights.specs.core3_archive
DEBUG:insights.core.dr:Importing insights.specs.sos_archive
DEBUG:insights.core.dr:Importing insights.specs.jdr_archive
DEBUG:insights.core.dr:Importing insights.specs.must_gather_archive
INFO:insights.core.dr:Trying insights.specs.Specs.redhat_release
DEBUG:insights.core.dr:insights.specs.Specs.redhat_release missing requirements All: [] Any: []
INFO:insights.core.dr:Trying insights.parsers.redhat_release.RedhatRelease
DEBUG:insights.core.dr:insights.parsers.redhat_release.RedhatRelease missing requirements All: ['insights.specs.Specs.redhat_release'] Any: 
Missing Dependencies:
    Requires:
        insights.specs.Specs.redhat_release
~~~

**Comment by jholecek-rh** [comment]
I suppose `insights.contrib.pyparsing` is kept for compatibility with Python 2.7. The module uses `collections.MutableMapping` and `collections.Sequence`, both of which have been moved to `collections.abc` quite some time ago and eventually removed from `collections` in Python 3.10.

A conditional import at https://github.com/RedHatInsights/insights-core/blob/master/insights/contrib/pyparsing.py#L72 **should** do the trick

```
if system_version[:2] >= (3,10):
    import collections.abc as collections
else:
   import collections
```

This is as far as I can go. I've been unable to run all insights-core tests successfully even with Python 3.6 so far and I have no interest in playing with Python 2.

**Comment by ryan-blakley** [comment]
I created and linked a PR that should fix this issue, if everyone could review it.

**Comment by jholecek-rh** [comment]
Thanks for the proper fix, @ryan-blakley. Looks good to me.

I created https://github.com/RedHatInsights/insights-core/issues/3408 to discuss options to improve our ability to troubleshoot issues like this. If I had not tried importing `insights.specs.default` manually, I would never know what caused this issue.
