### ISSUE TITLE
the combiner mounts spend more than 2000s to parser data

### ISSUE THREAD

**Issue by chenlizhong** [RedHatInsights/insights-core#3610]
For IBM GPFS, there are internal and external mounts. Internal mounts are not in the output of command mount, but they are in /proc/mounts
 https://www.ibm.com/support/pages/gpfs-internal-and-external-mount-states

One example system, there are more than 40000 internal mount points in /proc/mounts file. The mounts combiner cost 2000s. It is big performance impact.

**Comment by xiangce** [comment]
Resolved by #3606
