### ISSUE TITLE
FileListing: `.` in file_path of the top dir was converted to slash '/'

### ISSUE THREAD

**Issue by xiangce** [RedHatInsights/insights-core#3635]
Hey @mohitkumarrh - I think this is a bug in the cooperation between the insights core vs the base module `ls_parser`, the insights core used the following `mangle` logic and replaced all of the `/` to `.` as the filename in the insights-archive:
https://github.com/RedHatInsights/insights-core/blob/8656cccc1cbe78e208ac5d1336503b33d447ef99/insights/util/mangle.py#L40
But it didn't record which `.` is a `mangled` dot from the slash.

However, the `FileListing` converted all the `.` back to the `/` and didn't consider whether it's an original `.` in the `file_path`:
https://github.com/RedHatInsights/insights-core/blob/8656cccc1cbe78e208ac5d1336503b33d447ef99/insights/core/__init__.py#L1722

So the path `/var/lib/pcp/pmdas/openmetrics/config.d` in the parser result was stored as `/var/lib/pcp/pmdas/openmetrics/config/d` by mistake.

Since recently, we met a couple of issues in the `ls_parser`, I'm planning to do some enhancement on it. 
Could you please wait for a while?

Sorry about the inconvenience.

_Originally posted by @xiangce in https://github.com/RedHatInsights/insights-core/issues/3620#issuecomment-1354458782_

**Comment by mohitkumarrh** [comment]
> ```
>     Hey @mohitkumarrh - I think this is a bug in the cooperation between the insights core vs the base module `ls_parser`, the insights core used the following `mangle` logic and replaced all of the `/` to `.` as the filename in the insights-archive:
> ```
> 
> https://github.com/RedHatInsights/insights-core/blob/8656cccc1cbe78e208ac5d1336503b33d447ef99/insights/util/mangle.py#L40
> 
> 
> But it didn't record which `.` is a `mangled` dot from the slash.
> However, the `FileListing` converted all the `.` back to the `/` and didn't consider whether it's an original `.` in the `file_path`:
> 
> https://github.com/RedHatInsights/insights-core/blob/8656cccc1cbe78e208ac5d1336503b33d447ef99/insights/core/__init__.py#L1722
> 
> So the path `/var/lib/pcp/pmdas/openmetrics/config.d` in the parser result was stored as `/var/lib/pcp/pmdas/openmetrics/config/d` by mistake.
> 
> Since recently, we met a couple of issues in the `ls_parser`, I'm planning to do some enhancement on it. Could you please wait for a while?
> 
> Sorry about the inconvenience.
> 
> _Originally posted by @xiangce in [#3620 (comment)](https://github.com/RedHatInsights/insights-core/pull/3620#issuecomment-1354458782)_

@xiangce - I understand the bug now, I'll wait for the enhancement to be done to resolve this bug and change the MR accordingly.
