### ISSUE TITLE
InstalledRpms parser is implementing logic by try-except  and checking for each line

### ISSUE THREAD

**Issue by chenlizhong** [RedHatInsights/insights-core#3650]
Two issues are in below code:

1. It is using from_json  to load first, after failed, use the from_line
2. Do above  for each line. if the file has 1000 lines, these will occur 1000 times

https://github.com/RedHatInsights/insights-core/blob/c62d7dd1659625e250b957b80774b96585b21288/insights/parsers/installed_rpms.py#L256-L272

Suggestion:
Do file  content checking before the  loop to determine from_json or from_line at the beginning.

**Comment by xiangce** [comment]
resolved by https://github.com/RedHatInsights/insights-core/pull/3651
