### ISSUE TITLE
Spec modinfo_filtered_modules will raise CalledProcessError when the target module is not found 

### ISSUE THREAD

**Issue by wushiqinlou** [RedHatInsights/insights-core#3671]
The spec `modinfo_filtered_modules` is trying to collect `modinfo <modules>`. However, if the target module is not found, the command `modinfo <target module>` will return `modinfo: ERROR: Module <target module> not found.` and the error code is 1. Then the spec will stop collecting and raise CalledProcessError. However, this spec should collect the modinfo of the existing modules.

**Comment by xiangce** [comment]
resolved by #3670
