### ISSUE TITLE
`InstalledRpms` parser is unable to parse the file `rpm-qa` when it contains a warning

### ISSUE THREAD

**Issue by r14chandra** [RedHatInsights/insights-core#3769]
It is related to the issue - [RHINENG-365](https://issues.redhat.com/browse/RHINENG-365)

While debugging I found that the customer archive works fine when `rpm_-qa*` file doesn't contain a warning.

```
warning: Signature not supported. Hash algorithm SHA1 not available.
{"name":"gpg-pubkey","epoch":"(none)","version":"fd431d51","release":"4ae0493b","arch":"(none)","installtime":"Tue Feb 23 08:27:53 2021","buildtime":"1256212795","vendor":"(none)","buildhost":"localhost","sigpgp":"(none)"} 
```

The `InstalledRpms` parser is unable to parse the data.

**Comment by xiangce** [comment]
@r14chandra - Thanks a lot for reporting this bug. I believe this is caused by that the first line is a `warning` in the `rpm -qa *` command. I'll fix it soon.
