### ISSUE TITLE
The store_skips argument of run_input_data has no effect

### ISSUE THREAD

**Issue by jholecek-rh** [RedHatInsights/insights-core#3928]
**How to reproduce**

```
from insights.core.plugins import component
from insights.core.exceptions import SkipComponent
from insights.tests import InputData
from insights.tests import run_input_data

@component()
def some_component():
    raise SkipComponent

broker = run_input_data(some_component, InputData(), store_skips=True)
print(len(broker.exceptions))
```

**Current behavior**

`len(broker.exceptions) == 0`

**Expected behavior**

`len(broker.exceptions) == 1`

**Root cause**

The `broker.store_skips` property is set **after** the dependency graph execution.  It has to be set **before** the graph execution.

**Comment by xiangce** [comment]
Resolved by #3929
