### ISSUE TITLE
Redation causes false positive

### ISSUE THREAD

**Issue by wushiqinlou** [RedHatInsights/insights-core#4075]
The `ssl.conf` file contains this line:

~~~
SSLCertificateKeyFile /etc/pki/tls/private/linux.dts.star.oakland.edu.key.pem.withoutpassword
~~~

Redaction adds `********` under the line, which breaks the file format and leads the parser failure.

~~~
SSLCertificateKeyFile /etc/pki/tls/private/linux.dts.star.oakland.edu.key.pem.withoutpassword
********
~~~

The redaction should not work for this case.

**Comment by xiangce** [comment]
Resolved by https://github.com/RedHatInsights/insights-core/pull/4074 and then https://github.com/RedHatInsights/insights-core/pull/4130
