### ISSUE TITLE
Enhance `simple_command` to close stdin to avoid this class of bugs in the future.

### ISSUE THREAD

**Issue by xiangce** [RedHatInsights/insights-core#4187]
I'd suggest to enhance `simple_command` to close stdin to avoid this class of bugs in the future.

_Originally posted by @ekohl in https://github.com/RedHatInsights/insights-core/pull/4186#pullrequestreview-2229861161_
            
For more details see:
- https://github.com/theforeman/foreman/pull/10267
- RHINENG-11883

**Comment by ShimShtein** [comment]
I think closing the stdin can also influence the caller process, which is undesirable.

Maybe the `simple_command` should use the equivalent of ruby's [popen3](https://rubyapi.org/3.3/o/open3#method-i-popen3): 
> Creates streams stdin, stdout, and stderr, which are the standard input, standard output, and standard error streams in the child process.

This way the child process would be completely isolated from the caller.
