### ISSUE TITLE
The default value of strip from function context_wrap should not be True

### ISSUE THREAD

**Issue by wushiqinlou** [RedHatInsights/insights-core#4322]
When executing insights-run, the parser `OdCpuDmaLatency` fails to parse the following output:

~~~
     100000
~~~

The reason is `if content and content[0].isdigit():` is false as `content[0] is "     100000"`. 
However, py.test works well. The reason is that `context_wrap` applies strip before parsing logic.
To avoid such issue, the default strip from function context_wrap should not be True

**Comment by xiangce** [comment]
After a further discussion with @wushiqinlou, we both agree with that:

1. Do not modify the default value of the kwarg `strip=True` to the `context_wrap` method. As it will impact too many existing unit tests.
2. For the cases, e.g. the OdCpuDmaLatency, to keep its original content value which includes a staring whitespace, we'd use `context_wrap(CONTENT, strip=False)`

Closing this issue per this agreement.
