### ISSUE TITLE
Collect insights client configuration with blacklist

### ISSUE THREAD

**Issue by csams** [RedHatInsights/insights-core#588]
Collect insights client configuration to understand spec blacklist usage.

**Comment by JoySnow** [comment]
Hi, I am quite interested in this issue.
May I know that 
1. Will this feature be shipped with 3.x client?
2. How will the blacklist be applied?

**Comment by miclark** [comment]
Closing do to inactivity as well as the concern that collecting blacklist information may capture passwords and sensitive userids.
