### ISSUE TITLE
Specs may work differently when extracting from an archive vs in the Insights client.

### ISSUE THREAD

**Issue by bfahr** [RedHatInsights/insights-core#594]
Specs are used for extracting from an archive in a regex context, but they are used differently by the client for collection due to this, a patternspec may be specified that works in the regex context only.
So we can’t collect it from customer’s machines since the dirname portion is treated literally.

We might have to tweak pattern files to take two inputs.. *or* push people to start using globs.

This is in reference to PRs #579 and #580.

**Comment by miclark** [comment]
Based on old-style specs, no longer applicable.
