### ISSUE TITLE
SysconfigKdump parser missing from master branch

### ISSUE THREAD

**Issue by miclark** [RedHatInsights/insights-core#670]
In the 1.x branch, the `kdump.py` parser contains a `SysconfigKdump` class.  This class does not exist in the master branch, although the docstring of `kdump.py` lists it.   We need to port the parser class to the master branch.

**Comment by xiangce** [comment]
Hi @miclark, the `SysconfigKdump` in 1.x branch is deprecated and the `KdumpSysconfig` in `insights/parsers/sysconfig.py` is its new replacement in 3.x.

**Comment by csams** [comment]
The [kdump_hang_hp_bl460c_g7 rule](https://github.com/RedHatInsights/insights-plugins/blob/master/telemetry/rules/plugins/kdump/kdump_hang_hp_bl460c_g7.py#L74) has a bug since it uses the deprecated `kdump.SysconfigKdump` without actually depending on it. I'll open an issue in the plugins repo.
