### ISSUE TITLE
Possible parser error in `rabbitmq.py`

### ISSUE THREAD

**Issue by miclark** [RedHatInsights/insights-core#680]
Testing against production archives, the following exception occurred 19 times:
```
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 635, in run
    result = DELEGATES[component](broker)
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 594, in __f
    return executor(func, broker, requires, optional)
  File "build/bdist.linux-x86_64/egg/insights/core/plugins.py", line 29, in parser_executor
    return component(dep_value)
  File "build/bdist.linux-x86_64/egg/insights/core/__init__.py", line 90, in __init__
    self.parse_content(context.content)
  File "build/bdist.linux-x86_64/egg/insights/parsers/rabbitmq.py", line 195, in parse_content
    raise ParseException("Data appears invalid: {0}".format(line))
ParseException: Data appears invalid: ...done.
```
In this case, the parser is returning a `ParseException`, usually meaning an unexpected thing occurred.  So, if `...done` is truly unexpected, this may be okay.  Otherwise, we should handle it, returning `None` if it means the file should not be considered meaningful to any plugins.

**Comment by PaulWay** [comment]
Hi @miclark - I've taken a guess from some of the other `rabbitmqctl` outputs and excluded the '...done.' line fro processing.  I've also made a few improvements to the parsers.  This work is in https://github.com/RedHatInsights/insights-core/pull/829 - let me know what you think.

It'd be really useful to supply these reports with the actual data that caused the problem, if that can be arranged :-)

**Comment by miclark** [comment]
@PaulWay when we refocus on this after the 3.x migration, there will be an api and script to pull example archives that cause the errors found in the report.

Closing as a stale bug to be reconsidered if reported after 3.x migration.
