### ISSUE TITLE
Evaluate including psutil with Insights

### ISSUE THREAD

**Issue by csams** [RedHatInsights/insights-core#689]
[psutil](https://github.com/giampaolo/psutil) is worth checking out. It could be a huge help when writing data sources.

> psutil (process and system utilities) is a cross-platform library for retrieving information on running processes and system utilization (CPU, memory, disks, network, sensors) in Python. It is useful mainly for system monitoring, profiling and limiting process resources and management of running processes. It implements many functionalities offered by UNIX command line tools such as: ps, top, lsof, netstat, ifconfig, who, df, kill, free, nice, ionice, iostat, iotop, uptime, pidof, tty, taskset, pmap.

It's also cross platform.

**Comment by jhjaggars** [comment]
The sticking point is that it is c code which is a no-go for the noarch requirement.
