### ISSUE TITLE
Spec for command `modinfo` : remove OR enhance ?

### ISSUE THREAD

**Issue by JoySnow** [RedHatInsights/insights-core#730]
In both 1.x and 3.x(master), we have spec for `modinfo`, here: 
```
"modinfo"                   : CommandSpec("/usr/sbin/modinfo {module}", module=r"\S+"),
```
This item has a pre_command `"module"  : "/bin/ls /sys/module", ` .

Currently, no parser for this item, and this line is added with the Initial commit. 
So, should we remove it?
if not, we need correct it with cmd "/sbin/modinfo" and reward it with new parser.

**Comment by csams** [comment]
@kylape @jhjaggars @JoySnow I can't find any parser or rule in any repo that needs this right now. Since it executes a command for every module on the system, but that info isn't used by anything, I'm going to remove the datasource in 3.x, and we can add it back if we need it.

**Comment by JoySnow** [comment]
@csams It's okay to me.

**Comment by csams** [comment]
Done in 481134eb8dca17284188ca2fc8b32f579f2540f3.

**Comment by jsvob** [comment]
@csams Can we get it back, please? 

Relevant to https://github.com/RedHatInsights/insights-core/issues/1793

**Comment by jsvob** [comment]
We've agreed not to do that.
