### ISSUE TITLE
Research options around customer notifications for updated uploader.json/egg

### ISSUE THREAD

**Issue by jnewton75** [RedHatInsights/insights-core#774]
Per this BZ (https://bugzilla.redhat.com/show_bug.cgi?id=1516729), one of the items mentioned was the following: "Customer want to get notification when something new is rolled out to have the ability to exclude the new rule/command and run some tests before having it run on all systems"

Kyle had a few thoughts which were:
1. Changes are pushed to a public github repo.  Can we somehow get customers to follow changes in that repo?
2. Add a notification via our new webhook functionality in the API 
3. Set up a public mailing list and add a step to post to it after releasing a new uploader.json/e

**Comment by miclark** [comment]
Seems like a QE issue.
