### ISSUE TITLE
Documentation referring to old parser requirement syntax

### ISSUE THREAD

**Issue by PaulWay** [RedHatInsights/insights-core#791]
http://insights-core.readthedocs.io/en/latest/ruletut_rule.html gives the example line for creating a rule using the decorator:
```python
@rule(requires=[InstalledRpms, Lsof, Netstat])
def heartburn(local, shared):
```
This is the old v1 format, and should be:
```python
@rule(InstalledRpms, Lsof, Netstat)
def heartburn(rpm, lsof, netstat):
```
In addition, several of the examples use the wrong syntax (e.g. `@rule(requires=[rpm, lsof, netstat])`, which refers to non-existent parser names).

**Comment by jhjaggars** [comment]
I've updated this.
