### ISSUE TITLE
Remove 1.x spec handling from 3.x

### ISSUE THREAD

**Issue by csams** [RedHatInsights/insights-core#808]
Remove the old specs from 3.x: both generation of uploader.json and using them to extract files from archives.

**Comment by jhjaggars** [comment]
The plan here is to support simple files, simple commands and globs from current (1.x) archives.  This should already "just work" by specifying the root of the filesystem.  Any 1.x spec features outside of those already listed will no longer be supported.

**Comment by csams** [comment]
Done as part of #916
