### ISSUE TITLE
`FileListing` ignores `ls` listings that don't contain the name of the directory.

### ISSUE THREAD

**Issue by jsvob** [RedHatInsights/insights-core#827]
If an `ls` listing doesn't contain the name of the directory before the individual files, it skips the files.

https://github.com/RedHatInsights/insights-core/blob/f89748ffabc7a4b24159c9ccfdee2067bfab1c47/insights/core/__init__.py#L1046

The test shows that this is indeed intentional:
https://github.com/RedHatInsights/insights-core/blob/master/insights/tests/test_file_listing.py#L60

A listing of a single directory doesn't print the header with the directory name:

```
$ ls -la /var/www
total 0
drwxr-xr-x.  4 root root  33 Dec 15 08:12 .
drwxr-xr-x. 20 root root 278 Dec 15 08:12 ..
drwxr-xr-x.  2 root root   6 Oct  3 09:37 cgi-bin
drwxr-xr-x.  2 root root   6 Oct  3 09:37 html
```

When multiple directories are specified, or when the `-R` option is used, the directory names are printed:
```
ls -laR /var/www
/var/www:
total 0
drwxr-xr-x.  4 root root  33 Dec 15 08:12 .
drwxr-xr-x. 20 root root 278 Dec 15 08:12 ..
drwxr-xr-x.  2 root root   6 Oct  3 09:37 cgi-bin
drwxr-xr-x.  2 root root   6 Oct  3 09:37 html

/var/www/cgi-bin:
total 0
drwxr-xr-x. 2 root root  6 Oct  3 09:37 .
drwxr-xr-x. 4 root root 33 Dec 15 08:12 ..

/var/www/html:
total 0
drwxr-xr-x. 2 root root  6 Oct  3 09:37 .
drwxr-xr-x. 4 root root 33 Dec 15 08:12 ..
```

In order to work around the limitation, there are currently three options:

* using a spec like `ls -la /var/www /var/www` - specify the directory twice, it is printed twice and with the directory name
* listing e.g. /dev/null - `ls -la /var/www /dev/null`
* using the `-R` switch - `ls -laR /var/www`

The first two are inelegant. The third one cannot be used in some scenarios, like in the example - if a rule needs only first-level information about the contents of /var/www, I don't want to go recursively, because there *might* be millions of files (performance reasons) and because there might be data that the rule doesn't need and will just needlessly gather potentially sensitive information only to discard it later.

So the issue is that `FileListing` should support simple one-directory listings that don't contain the directory name.

EDIT: I mistakenly hit enter during filing the issue, so I edited it to finish it.

**Comment by PaulWay** [comment]
OK, let me have a look at that and see if I can improve it.  I think the method would be to try to extract the target directory from the source command or file name first, and then if we read a directory name from the input we use that instead.

**Comment by PaulWay** [comment]
This has now been merged, we're good now.
