### ISSUE TITLE
Remove direct dependency on netstat

### ISSUE THREAD

**Issue by matysek** [RedHatInsights/insights-core#83]
From netstat man page:
```
This program is mostly obsolete. Replacement for netstat is ss. Replacement for netstat -r is ip route. Replacement for netstat -i is ip -s link. Replacement for netstat -g is ip maddr.
```

**Comment by jhjaggars** [comment]
I'm a little fuzzy on the details, but older versions of ss (say in RHEL6) are incredibly slow so I'm hesitant to outright replace netstat calls with ss calls w/o some testing on our supported platforms.

**Comment by kylape** [comment]
FWIW a quick check on a stock RHEL 6 box shows that `ss` is installed.

**Comment by miclark** [comment]
Closing this until we have a clearer picture of the removal of netstat.
