### ISSUE TITLE
dirsrv_access and dirsrv_errors will never collect

### ISSUE THREAD

**Issue by kylape** [RedHatInsights/insights-core#891]
The following specs will not work:

https://github.com/RedHatInsights/insights-core/blob/e76aeaa2532a0a1d4b85d01a3588670ccdd12804/insights/config/specs.py#L80-L81

The `.*` in the directory name will be interpreted literally (i.e. not as a regex), thus will never collect anything.  The solution is to come up with a set of reasonable values and stick each on in as a separate spec for directory names.  3.x will have much better solutions to this problem.

**Comment by PaulWay** [comment]
Yet another vote for https://github.com/RedHatInsights/insights-core/issues/413 I see :-)

Can you show me where in the documentation it talks about how the PatternSpec works, and what patterns it accepts?  Globs?  Regular expressions?  That way I know how this is actually supposed to work and can adjust the pattern to suit.

**Comment by csams** [comment]
dirsrv_errors has been updated in the uploader.json
