### ISSUE TITLE
`add_filter` is completely undocumented

### ISSUE THREAD

**Issue by PaulWay** [RedHatInsights/insights-core#927]
The `add_filter` function is being used in many parsers:
```$ ag add_filter insights/parsers
insights/parsers/tests/test_messages.py
1:from insights import add_filter
18:add_filter(Specs.messages, [

insights/parsers/tests/test_rhsm_log.py
1:from insights import add_filter
21:add_filter(Specs.rhsm_log, [

insights/parsers/tests/test_secure.py
1:from insights import add_filter
21:add_filter("secure", [

insights/parsers/tests/test_journal_since_boot.py
1:from insights.core.filters import add_filter
18:add_filter("messages", [

insights/parsers/tests/test_audit_log.py
2:from insights import add_filter
52:add_filter("audit_log", [

insights/parsers/tests/test_httpd_conf.py
1:from insights import add_filter
143:add_filter(Specs.httpd_conf, [

insights/parsers/virt_who_conf.py
14:from .. import parser, LegacyItemAccess, IniConfigFile, add_filter
29:add_filter(Specs.virt_who_conf, filter_list)

insights/parsers/katello_service_status.py
26:from .. import parser, Parser, add_filter
29:add_filter(Specs.katello_service_status, ['Some services failed to status',

insights/parsers/lvm.py
34:from .. import add_filter
560:add_filter(Specs.lvm_conf, LVM_CONF_FILTERS)

insights/parsers/lsof.py
63:from .. import add_filter, Scannable, parser
66:add_filter(Specs.lsof, ['COMMAND'])

insights/parsers/samba.py
1:from .. import add_filter, IniConfigFile, parser
4:add_filter(Specs.samba, ["["])

insights/parsers/audit_log.py
8:from .. import LogFileOutput, parser, add_filter
17:add_filter(Specs.audit_log, filter_list)

insights/parsers/ps.py
70:from insights.core.filters import add_filter
211:add_filter(Specs.ps_aux, "COMMAND")

```
Yet it is undocumented:
```
$ ag add_filter docs/
$
```
It is mentioned in passing in the Rule Migration Guide:
```
ag add_filter notebooks/
notebooks/Rule Migration Guide.ipynb
33:    "from insights.core.filters import add_filter\n",
36:    "add_filter(Specs.messages, \"KEEP_ME\")\n",
37:    "add_filter(Specs.messages, [\"KEEUP_US\", \"KEEP_US_TOO\"])\n",
```
But the rule migration guide is not referenced from the documentation either:
```
$ ag 'Rule Migration Guide' docs/
$
```
This seems to be an important feature that is not documented.

It's also concerning because `add_filter` is being applied to parsers like `PsAuxww` which rule writers have treated (up until now) as containing the entire process list with no filtering.  The documentation of `PsAuxww` does not indicate that it is necessary to add filters in order to get the processes that a rule is interested in.  Does `add_filter` actually only include lines that are filtered?  How does it work?  Where should it be used and why?  All this is undocumented.

**Comment by csams** [comment]
Now documented with a [tutorial](https://github.com/RedHatInsights/insights-core/blob/master/docs/notebooks/Filters%20Tutorial.ipynb) and at [read the docs](http://insights-core.readthedocs.io/en/latest/api_index.html#module-insights.core.filters). We're also making filterable datasources [more explicit and harder to misuse](https://github.com/RedHatInsights/insights-core/pull/1332).
