### ISSUE TITLE
Add check for brctl "No such file or directory"

### ISSUE THREAD

**Issue by vishwanathjadhav** [RedHatInsights/insights-core#988]
There are some archives where it is noticed that the ``brctl show`` command not found, but the error message is different ``timeout: failed to run command `/usr/sbin/brctl': No such file or directory``. Need to add a check for such error message.

**Comment by csams** [comment]
Fixed in master in 0e0bb08f73867bf76e0fb539843c535e0aabeea6. Changes for 1.x are no longer being accepted.
