### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by csams** [RedHatInsights/insights-core#996]
All parsers that inherit from JSONParser (or any other parser with a base class in `insights.core`) may raise exceptions, but because they're raised from the base class, we can't tell which concrete parser raised them. I suspect the root of the problem will be solved when data sources handle bad command invocations more intelligently, but it's still a general problem we should look into for error reporting.

**Comment by bfahr** [comment]
PR #1312 has been merged into master and 3.0 branches.
